using PKHeX.Core;
using System;
using System.Collections.Generic;
using System.IO;

namespace Chatbot_TextStrings
{
    public static class YT_Forms
    {
        public class FormIdentifier
        {
            public bool Valid { get; set; }
            public string? FormFileName { get; set; }
            public int FormID { get; set; }
            public PKM? PK { get; set; }
        }

        private static EntityContext GetEntityContext(int Generation)
        {
            return Generation switch
            {
                1 => EntityContext.Gen1,
                2 => EntityContext.Gen2,
                3 => EntityContext.Gen3,
                4 => EntityContext.Gen4,
                5 => EntityContext.Gen5,
                6 => EntityContext.Gen6,
                7 => EntityContext.Gen7,
                77 => EntityContext.Gen7b,
                8 => EntityContext.Gen8,
                88 => EntityContext.Gen8b,
                888 => EntityContext.Gen8a,
                9 => EntityContext.Gen9,
                _ => EntityContext.Gen8
            };
        }

        /// <summary>
        /// Returns the Form Identifier and the Species Name.
        /// </summary>
        /// <param name="Nickname">Nicknamed Pokemon from User</param>
        /// <returns>Formated Nickname Identifier and PKHEX Formated Species Name</returns>
        public static FormIdentifier GetFormIdentifier(int game, string Nickname)
        {
            try
            {
                string FolderName = "";
                string Extension = "";
                string FormFile = "";

                switch (game)
                {
                    case 6:
                        FolderName = "Pokemon6";
                        Extension = "pk6";
                        break;
                    case 7:
                    case 88:
                        FolderName = "Pokemon";
                        Extension = "pk7";
                        break;
                    case 8:
                        FolderName = "Pokemon8";
                        Extension = "pk8";
                        break;
                    case 888:
                        FolderName = "Pokemon8a";
                        Extension = "pa8";
                        break;
                    default:
                        break;
                }

                bool containsDigitForm = int.TryParse(Nickname[..1], out int _);

                FormInfo? form = GetForm(Nickname);

                if (form is null)
                {
                    //Console.WriteLine("Unable to get specific Form");
                    return new FormIdentifier()
                    {
                        Valid = false,
                        FormFileName = String.Empty,
                        PK = null,
                        FormID = -1
                    };
                }

                FormFile = $"C:\\{FolderName}\\{form.Species}\\{form.FormName.ToLower()}.{Extension}";

                if (File.Exists(FormFile))
                {
                    PKM? pk = EntityFormat.GetFromBytes(File.ReadAllBytes(FormFile), GetEntityContext(game));
                    if (pk != null)
                    {
                        return new FormIdentifier()
                        {
                            Valid = true,
                            FormFileName = Path.GetFileName(FormFile).Replace($".{Extension}", ""),
                            PK = pk,
                            FormID = pk.Form
                        };
                    }
                }
                return new FormIdentifier()
                {
                    Valid = false,
                    FormFileName = Path.GetFileName(FormFile).Replace($".{Extension}", ""),
                    PK = null,
                    FormID = -1
                };
            }

            catch (Exception ex)
            {
                Console.WriteLine("Exception: " + ex.ToString());
                return new FormIdentifier()
                {
                    Valid = false,
                    FormFileName = String.Empty,
                    PK = null,
                    FormID = -1
                };
            }
        }

        private static FormInfo? GetForm(string form)
        {
            try
            {
                return NicknameForms[form];
            }
            catch { return null; }
        }

        public class FormInfo
        {
            public string? FormName { get; set; }
            public Species Species { get; set; }
        }

        // TODO: Remove once Home gets released
        public readonly static HashSet<Species> LockedHisuiForms = new()
        {
            Species.Decidueye,
            Species.Typhlosion,
            Species.Samurott,
            Species.Arcanine,
            Species.Growlithe,
            Species.Avalugg,
            Species.Braviary,
            Species.Electrode,
            Species.Voltorb,
            Species.Goodra,
            Species.Sliggoo,
            Species.Qwilfish,
            Species.Zoroark,
            Species.Zorua,
            Species.Lilligant,
        };


        private readonly static Dictionary<string, FormInfo> NicknameForms = new()
        {
            { "19a", new FormInfo { FormName = "alola", Species = Species.Rattata } },
            { "rattataa", new FormInfo { FormName = "alola", Species = Species.Rattata } },
            { "20a", new FormInfo { FormName = "alola", Species = Species.Raticate } },
            { "raticatea", new FormInfo { FormName = "alola", Species = Species.Raticate } },
            { "20t", new FormInfo { FormName = "totem", Species = Species.Raticate } },
            { "raticatet", new FormInfo { FormName = "totem", Species = Species.Raticate } },
            { "25o", new FormInfo { FormName = "original", Species = Species.Pikachu } },
            { "pikachuo", new FormInfo { FormName = "original", Species = Species.Pikachu } },
            { "25h", new FormInfo { FormName = "hoenn", Species = Species.Pikachu } },
            { "pikachuh", new FormInfo { FormName = "hoenn", Species = Species.Pikachu } },
            { "25s", new FormInfo { FormName = "sinnoh", Species = Species.Pikachu } },
            { "pikachus", new FormInfo { FormName = "sinnoh", Species = Species.Pikachu } },
            { "25u", new FormInfo { FormName = "unova", Species = Species.Pikachu } },
            { "pikachuu", new FormInfo { FormName = "unova", Species = Species.Pikachu } },
            { "25k", new FormInfo { FormName = "kalos", Species = Species.Pikachu } },
            { "pikachuk", new FormInfo { FormName = "kalos", Species = Species.Pikachu } },
            { "25a", new FormInfo { FormName = "alola", Species = Species.Pikachu } },
            { "pikachua", new FormInfo { FormName = "alola", Species = Species.Pikachu } },
            { "25p", new FormInfo { FormName = "partner", Species = Species.Pikachu } },
            { "pikachup", new FormInfo { FormName = "partner", Species = Species.Pikachu } },
            { "25w", new FormInfo { FormName = "world", Species = Species.Pikachu } },
            { "pikachuw", new FormInfo { FormName = "world", Species = Species.Pikachu } },
            { "26a", new FormInfo { FormName = "alola", Species = Species.Raichu } },
            { "raichua", new FormInfo { FormName = "alola", Species = Species.Raichu } },
            { "27a", new FormInfo { FormName = "alola", Species = Species.Sandshrew } },
            { "sandshrewa", new FormInfo { FormName = "alola", Species = Species.Sandshrew } },
            { "28a", new FormInfo { FormName = "alola", Species = Species.Sandslash } },
            { "sandslasha", new FormInfo { FormName = "alola", Species = Species.Sandslash } },
            { "37a", new FormInfo { FormName = "alola", Species = Species.Vulpix } },
            { "vulpixa", new FormInfo { FormName = "alola", Species = Species.Vulpix } },
            { "38a", new FormInfo { FormName = "alola", Species = Species.Ninetales } },
            { "ninetalesa", new FormInfo { FormName = "alola", Species = Species.Ninetales } },
            { "50a", new FormInfo { FormName = "alola", Species = Species.Diglett } },
            { "digletta", new FormInfo { FormName = "alola", Species = Species.Diglett } },
            { "51a", new FormInfo { FormName = "alola", Species = Species.Dugtrio } },
            { "dugtrioa", new FormInfo { FormName = "alola", Species = Species.Dugtrio } },
            { "52a", new FormInfo { FormName = "alola", Species = Species.Meowth } },
            { "meowtha", new FormInfo { FormName = "alola", Species = Species.Meowth } },
            { "52g", new FormInfo { FormName = "galar", Species = Species.Meowth } },
            { "meowthg", new FormInfo { FormName = "galar", Species = Species.Meowth } },
            { "53a", new FormInfo { FormName = "alola", Species = Species.Persian } },
            { "persiana", new FormInfo { FormName = "alola", Species = Species.Persian } },
            { "58h", new FormInfo { FormName = "hisui", Species = Species.Growlithe } },
            { "growlitheh", new FormInfo { FormName = "hisui", Species = Species.Growlithe } },
            { "59h", new FormInfo { FormName = "hisui", Species = Species.Arcanine } },
            { "arcanineh", new FormInfo { FormName = "hisui", Species = Species.Arcanine } },
            { "74a", new FormInfo { FormName = "alola", Species = Species.Geodude } },
            { "geodudea", new FormInfo { FormName = "alola", Species = Species.Geodude } },
            { "75a", new FormInfo { FormName = "alola", Species = Species.Graveler } },
            { "gravelera", new FormInfo { FormName = "alola", Species = Species.Graveler } },
            { "76a", new FormInfo { FormName = "alola", Species = Species.Golem } },
            { "golema", new FormInfo { FormName = "alola", Species = Species.Golem } },
            { "77g", new FormInfo { FormName = "galar", Species = Species.Ponyta } },
            { "ponytag", new FormInfo { FormName = "galar", Species = Species.Ponyta } },
            { "78g", new FormInfo { FormName = "galar", Species = Species.Rapidash } },
            { "rapidashg", new FormInfo { FormName = "galar", Species = Species.Rapidash } },
            { "79g", new FormInfo { FormName = "galar", Species = Species.Slowpoke } },
            { "slowpokeg", new FormInfo { FormName = "galar", Species = Species.Slowpoke } },
            { "80g", new FormInfo { FormName = "galar", Species = Species.Slowbro } },
            { "slowbrog", new FormInfo { FormName = "galar", Species = Species.Slowbro } },
            { "83g", new FormInfo { FormName = "galar", Species = Species.Farfetchd } },
            { "farfetchdg", new FormInfo { FormName = "galar", Species = Species.Farfetchd } },
            { "88a", new FormInfo { FormName = "alola", Species = Species.Grimer } },
            { "grimera", new FormInfo { FormName = "alola", Species = Species.Grimer } },
            { "89a", new FormInfo { FormName = "alola", Species = Species.Muk } },
            { "muka", new FormInfo { FormName = "alola", Species = Species.Muk } },
            { "100h", new FormInfo { FormName = "hisui", Species = Species.Voltorb } },
            { "voltorbh", new FormInfo { FormName = "hisui", Species = Species.Voltorb } },
            { "101h", new FormInfo { FormName = "hisui", Species = Species.Electrode } },
            { "electrodeh", new FormInfo { FormName = "hisui", Species = Species.Electrode } },
            { "103a", new FormInfo { FormName = "alola", Species = Species.Exeggutor } },
            { "exeggutora", new FormInfo { FormName = "alola", Species = Species.Exeggutor } },
            { "105a", new FormInfo { FormName = "alola", Species = Species.Marowak } },
            { "marowaka", new FormInfo { FormName = "alola", Species = Species.Marowak } },
            { "105t", new FormInfo { FormName = "totem", Species = Species.Marowak } },
            { "marowakt", new FormInfo { FormName = "totem", Species = Species.Marowak } },
            { "110g", new FormInfo { FormName = "galar", Species = Species.Weezing } },
            { "weezingg", new FormInfo { FormName = "galar", Species = Species.Weezing } },
            { "122g", new FormInfo { FormName = "galar", Species = Species.MrMime } },
            { "mrmimeg", new FormInfo { FormName = "galar", Species = Species.MrMime } },
            { "144g", new FormInfo { FormName = "galar", Species = Species.Articuno } },
            { "articunog", new FormInfo { FormName = "galar", Species = Species.Articuno } },
            { "145g", new FormInfo { FormName = "galar", Species = Species.Zapdos } },
            { "zapdosg", new FormInfo { FormName = "galar", Species = Species.Zapdos } },
            { "146g", new FormInfo { FormName = "galar", Species = Species.Moltres } },
            { "moltresg", new FormInfo { FormName = "galar", Species = Species.Moltres } },
            { "157h", new FormInfo { FormName = "hisui", Species = Species.Typhlosion } },
            { "typhlosionh", new FormInfo { FormName = "hisui", Species = Species.Typhlosion } },
            { "199g", new FormInfo { FormName = "galar", Species = Species.Slowking } },
            { "slowkingg", new FormInfo { FormName = "galar", Species = Species.Slowking } },
            { "201a", new FormInfo { FormName = "a", Species = Species.Unown } },
            { "unowna", new FormInfo { FormName = "a", Species = Species.Unown } },
            { "201b", new FormInfo { FormName = "b", Species = Species.Unown } },
            { "unownb", new FormInfo { FormName = "b", Species = Species.Unown } },
            { "201c", new FormInfo { FormName = "c", Species = Species.Unown } },
            { "unownc", new FormInfo { FormName = "c", Species = Species.Unown } },
            { "201d", new FormInfo { FormName = "d", Species = Species.Unown } },
            { "unownd", new FormInfo { FormName = "d", Species = Species.Unown } },
            { "201e", new FormInfo { FormName = "e", Species = Species.Unown } },
            { "unowne", new FormInfo { FormName = "e", Species = Species.Unown } },
            { "201f", new FormInfo { FormName = "f", Species = Species.Unown } },
            { "unownf", new FormInfo { FormName = "f", Species = Species.Unown } },
            { "201g", new FormInfo { FormName = "g", Species = Species.Unown } },
            { "unowng", new FormInfo { FormName = "g", Species = Species.Unown } },
            { "201h", new FormInfo { FormName = "h", Species = Species.Unown } },
            { "unownh", new FormInfo { FormName = "h", Species = Species.Unown } },
            { "201i", new FormInfo { FormName = "i", Species = Species.Unown } },
            { "unowni", new FormInfo { FormName = "i", Species = Species.Unown } },
            { "201j", new FormInfo { FormName = "j", Species = Species.Unown } },
            { "unownj", new FormInfo { FormName = "j", Species = Species.Unown } },
            { "201k", new FormInfo { FormName = "k", Species = Species.Unown } },
            { "unownk", new FormInfo { FormName = "k", Species = Species.Unown } },
            { "201l", new FormInfo { FormName = "l", Species = Species.Unown } },
            { "unownl", new FormInfo { FormName = "l", Species = Species.Unown } },
            { "201m", new FormInfo { FormName = "m", Species = Species.Unown } },
            { "unownm", new FormInfo { FormName = "m", Species = Species.Unown } },
            { "201n", new FormInfo { FormName = "n", Species = Species.Unown } },
            { "unownn", new FormInfo { FormName = "n", Species = Species.Unown } },
            { "201o", new FormInfo { FormName = "o", Species = Species.Unown } },
            { "unowno", new FormInfo { FormName = "o", Species = Species.Unown } },
            { "201p", new FormInfo { FormName = "p", Species = Species.Unown } },
            { "unownp", new FormInfo { FormName = "p", Species = Species.Unown } },
            { "201q", new FormInfo { FormName = "q", Species = Species.Unown } },
            { "unownq", new FormInfo { FormName = "q", Species = Species.Unown } },
            { "201r", new FormInfo { FormName = "r", Species = Species.Unown } },
            { "unownr", new FormInfo { FormName = "r", Species = Species.Unown } },
            { "201s", new FormInfo { FormName = "s", Species = Species.Unown } },
            { "unowns", new FormInfo { FormName = "s", Species = Species.Unown } },
            { "201t", new FormInfo { FormName = "t", Species = Species.Unown } },
            { "unownt", new FormInfo { FormName = "t", Species = Species.Unown } },
            { "201u", new FormInfo { FormName = "u", Species = Species.Unown } },
            { "unownu", new FormInfo { FormName = "u", Species = Species.Unown } },
            { "201v", new FormInfo { FormName = "v", Species = Species.Unown } },
            { "unownv", new FormInfo { FormName = "v", Species = Species.Unown } },
            { "201w", new FormInfo { FormName = "w", Species = Species.Unown } },
            { "unownw", new FormInfo { FormName = "w", Species = Species.Unown } },
            { "201x", new FormInfo { FormName = "x", Species = Species.Unown } },
            { "unownx", new FormInfo { FormName = "x", Species = Species.Unown } },
            { "201y", new FormInfo { FormName = "y", Species = Species.Unown } },
            { "unowny", new FormInfo { FormName = "y", Species = Species.Unown } },
            { "201z", new FormInfo { FormName = "z", Species = Species.Unown } },
            { "unownz", new FormInfo { FormName = "z", Species = Species.Unown } },
            { "201?", new FormInfo { FormName = "_FRAGEZEICHEN", Species = Species.Unown } },
            { "unown?", new FormInfo { FormName = "_FRAGEZEICHEN", Species = Species.Unown } },
            { "201!", new FormInfo { FormName = "_AUSRUFEZEICHEN", Species = Species.Unown } },
            { "unown!", new FormInfo { FormName = "_AUSRUFEZEICHEN", Species = Species.Unown } },
            { "211h", new FormInfo { FormName = "hisui", Species = Species.Qwilfish } },
            { "qwilfishh", new FormInfo { FormName = "hisui", Species = Species.Qwilfish } },
            { "215h", new FormInfo { FormName = "hisui", Species = Species.Sneasel } },
            { "sneaselh", new FormInfo { FormName = "hisui", Species = Species.Sneasel } },
            { "222g", new FormInfo { FormName = "galar", Species = Species.Corsola } },
            { "corsolag", new FormInfo { FormName = "galar", Species = Species.Corsola } },
            { "263g", new FormInfo { FormName = "galar", Species = Species.Zigzagoon } },
            { "zigzagoong", new FormInfo { FormName = "galar", Species = Species.Zigzagoon } },
            { "264g", new FormInfo { FormName = "galar", Species = Species.Linoone } },
            { "linooneg", new FormInfo { FormName = "galar", Species = Species.Linoone } },
            { "386a", new FormInfo { FormName = "attack", Species = Species.Deoxys } },
            { "deoxysa", new FormInfo { FormName = "attack", Species = Species.Deoxys } },
            { "386d", new FormInfo { FormName = "defense", Species = Species.Deoxys } },
            { "deoxysd", new FormInfo { FormName = "defense", Species = Species.Deoxys } },
            { "386s", new FormInfo { FormName = "speed", Species = Species.Deoxys } },
            { "deoxyss", new FormInfo { FormName = "speed", Species = Species.Deoxys } },
            { "412p", new FormInfo { FormName = "plant", Species = Species.Burmy } },
            { "burmyp", new FormInfo { FormName = "plant", Species = Species.Burmy } },
            { "412s", new FormInfo { FormName = "sandy", Species = Species.Burmy } },
            { "burmys", new FormInfo { FormName = "sandy", Species = Species.Burmy } },
            { "412t", new FormInfo { FormName = "trash", Species = Species.Burmy } },
            { "burmyt", new FormInfo { FormName = "trash", Species = Species.Burmy } },
            { "413p", new FormInfo { FormName = "plant", Species = Species.Wormadam } },
            { "wormadamp", new FormInfo { FormName = "plant", Species = Species.Wormadam } },
            { "413s", new FormInfo { FormName = "sandy", Species = Species.Wormadam } },
            { "wormadams", new FormInfo { FormName = "sandy", Species = Species.Wormadam } },
            { "413t", new FormInfo { FormName = "trash", Species = Species.Wormadam } },
            { "wormadamt", new FormInfo { FormName = "trash", Species = Species.Wormadam } },
            { "422e", new FormInfo { FormName = "east", Species = Species.Shellos } },
            { "shellose", new FormInfo { FormName = "east", Species = Species.Shellos } },
            { "422w", new FormInfo { FormName = "west", Species = Species.Shellos } },
            { "shellosw", new FormInfo { FormName = "west", Species = Species.Shellos } },
            { "423e", new FormInfo { FormName = "east", Species = Species.Gastrodon } },
            { "gastrodone", new FormInfo { FormName = "east", Species = Species.Gastrodon } },
            { "423w", new FormInfo { FormName = "west", Species = Species.Gastrodon } },
            { "gastrodonw", new FormInfo { FormName = "west", Species = Species.Gastrodon } },
            { "479h", new FormInfo { FormName = "heat", Species = Species.Rotom } },
            { "rotomh", new FormInfo { FormName = "heat", Species = Species.Rotom } },
            { "479w", new FormInfo { FormName = "wash", Species = Species.Rotom } },
            { "rotomw", new FormInfo { FormName = "wash", Species = Species.Rotom } },
            { "479fr", new FormInfo { FormName = "frost", Species = Species.Rotom } },
            { "rotomfr", new FormInfo { FormName = "frost", Species = Species.Rotom } },
            { "479fa", new FormInfo { FormName = "fan", Species = Species.Rotom } },
            { "rotomfa", new FormInfo { FormName = "fan", Species = Species.Rotom } },
            { "479m", new FormInfo { FormName = "mow", Species = Species.Rotom } },
            { "rotomm", new FormInfo { FormName = "mow", Species = Species.Rotom } },
            { "483o", new FormInfo { FormName = "origin", Species = Species.Dialga } },
            { "dialgao", new FormInfo { FormName = "origin", Species = Species.Dialga } },
            { "484o", new FormInfo { FormName = "origin", Species = Species.Palkia } },
            { "palkiao", new FormInfo { FormName = "origin", Species = Species.Palkia } },
            { "487o", new FormInfo { FormName = "origin", Species = Species.Giratina } },
            { "giratinao", new FormInfo { FormName = "origin", Species = Species.Giratina } },
            { "493n", new FormInfo { FormName = "normal", Species = Species.Arceus } },
            { "arceusn", new FormInfo { FormName = "normal", Species = Species.Arceus } },
            { "493fe", new FormInfo { FormName = "fire", Species = Species.Arceus } },
            { "arceusfe", new FormInfo { FormName = "fire", Species = Species.Arceus } },
            { "493w", new FormInfo { FormName = "water", Species = Species.Arceus } },
            { "arceusw", new FormInfo { FormName = "water", Species = Species.Arceus } },
            { "493e", new FormInfo { FormName = "electric", Species = Species.Arceus } },
            { "arceuse", new FormInfo { FormName = "electric", Species = Species.Arceus } },
            { "493gs", new FormInfo { FormName = "grass", Species = Species.Arceus } },
            { "arceusgs", new FormInfo { FormName = "grass", Species = Species.Arceus } },
            { "493i", new FormInfo { FormName = "ice", Species = Species.Arceus } },
            { "arceusi", new FormInfo { FormName = "ice", Species = Species.Arceus } },
            { "493ft", new FormInfo { FormName = "fighting", Species = Species.Arceus } },
            { "arceusft", new FormInfo { FormName = "fighting", Species = Species.Arceus } },
            { "493po", new FormInfo { FormName = "poison", Species = Species.Arceus } },
            { "arceuspo", new FormInfo { FormName = "poison", Species = Species.Arceus } },
            { "493gd", new FormInfo { FormName = "ground", Species = Species.Arceus } },
            { "arceusgd", new FormInfo { FormName = "ground", Species = Species.Arceus } },
            { "493fl", new FormInfo { FormName = "flying", Species = Species.Arceus } },
            { "arceusfl", new FormInfo { FormName = "flying", Species = Species.Arceus } },
            { "493ps", new FormInfo { FormName = "psychic", Species = Species.Arceus } },
            { "arceusps", new FormInfo { FormName = "psychic", Species = Species.Arceus } },
            { "493b", new FormInfo { FormName = "bug", Species = Species.Arceus } },
            { "arceusb", new FormInfo { FormName = "bug", Species = Species.Arceus } },
            { "493r", new FormInfo { FormName = "rock", Species = Species.Arceus } },
            { "arceusr", new FormInfo { FormName = "rock", Species = Species.Arceus } },
            { "493gt", new FormInfo { FormName = "ghost", Species = Species.Arceus } },
            { "arceusgt", new FormInfo { FormName = "ghost", Species = Species.Arceus } },
            { "493dr", new FormInfo { FormName = "dragon", Species = Species.Arceus } },
            { "arceusdr", new FormInfo { FormName = "dragon", Species = Species.Arceus } },
            { "493da", new FormInfo { FormName = "dark", Species = Species.Arceus } },
            { "arceusda", new FormInfo { FormName = "dark", Species = Species.Arceus } },
            { "493s", new FormInfo { FormName = "steel", Species = Species.Arceus } },
            { "arceuss", new FormInfo { FormName = "steel", Species = Species.Arceus } },
            { "493fa", new FormInfo { FormName = "fairy", Species = Species.Arceus } },
            { "arceusfa", new FormInfo { FormName = "fairy", Species = Species.Arceus } },
            { "493l", new FormInfo { FormName = "legend", Species = Species.Arceus } },
            { "arceusl", new FormInfo { FormName = "legend", Species = Species.Arceus } },
            { "503h", new FormInfo { FormName = "hisui", Species = Species.Samurott } },
            { "samurotth", new FormInfo { FormName = "hisui", Species = Species.Samurott } },
            { "549h", new FormInfo { FormName = "hisui", Species = Species.Lilligant } },
            { "lilliganth", new FormInfo { FormName = "hisui", Species = Species.Lilligant } },
            { "550r", new FormInfo { FormName = "red", Species = Species.Basculin } },
            { "basculinr", new FormInfo { FormName = "red", Species = Species.Basculin } },
            { "550b", new FormInfo { FormName = "blue", Species = Species.Basculin } },
            { "basculinb", new FormInfo { FormName = "blue", Species = Species.Basculin } },
            { "550w", new FormInfo { FormName = "white", Species = Species.Basculin } },
            { "basculinw", new FormInfo { FormName = "white", Species = Species.Basculin } },
            { "554g", new FormInfo { FormName = "galar", Species = Species.Darumaka } },
            { "darumakag", new FormInfo { FormName = "galar", Species = Species.Darumaka } },
            { "555g", new FormInfo { FormName = "galar", Species = Species.Darmanitan } },
            { "darmanitang", new FormInfo { FormName = "galar", Species = Species.Darmanitan } },
            { "562g", new FormInfo { FormName = "galar", Species = Species.Yamask } },
            { "yamaskg", new FormInfo { FormName = "galar", Species = Species.Yamask } },
            { "570h", new FormInfo { FormName = "hisui", Species = Species.Zorua } },
            { "zoruah", new FormInfo { FormName = "hisui", Species = Species.Zorua } },
            { "571h", new FormInfo { FormName = "hisui", Species = Species.Zoroark } },
            { "zoroarkh", new FormInfo { FormName = "hisui", Species = Species.Zoroark } },
            { "585sp", new FormInfo { FormName = "spring", Species = Species.Deerling } },
            { "deerlingsp", new FormInfo { FormName = "spring", Species = Species.Deerling } },
            { "585su", new FormInfo { FormName = "summer", Species = Species.Deerling } },
            { "deerlingsu", new FormInfo { FormName = "summer", Species = Species.Deerling } },
            { "585a", new FormInfo { FormName = "autumn", Species = Species.Deerling } },
            { "deerlinga", new FormInfo { FormName = "autumn", Species = Species.Deerling } },
            { "585w", new FormInfo { FormName = "winter", Species = Species.Deerling } },
            { "deerlingw", new FormInfo { FormName = "winter", Species = Species.Deerling } },
            { "586sp", new FormInfo { FormName = "spring", Species = Species.Sawsbuck } },
            { "sawsbucksp", new FormInfo { FormName = "spring", Species = Species.Sawsbuck } },
            { "586su", new FormInfo { FormName = "summer", Species = Species.Sawsbuck } },
            { "sawsbucksu", new FormInfo { FormName = "summer", Species = Species.Sawsbuck } },
            { "586a", new FormInfo { FormName = "autumn", Species = Species.Sawsbuck } },
            { "sawsbucka", new FormInfo { FormName = "autumn", Species = Species.Sawsbuck } },
            { "586w", new FormInfo { FormName = "winter", Species = Species.Sawsbuck } },
            { "sawsbuckw", new FormInfo { FormName = "winter", Species = Species.Sawsbuck } },
            { "618g", new FormInfo { FormName = "galar", Species = Species.Stunfisk } },
            { "stunfiskg", new FormInfo { FormName = "galar", Species = Species.Stunfisk } },
            { "628h", new FormInfo { FormName = "hisui", Species = Species.Braviary } },
            { "braviaryh", new FormInfo { FormName = "hisui", Species = Species.Braviary } },
            { "641t", new FormInfo { FormName = "therian", Species = Species.Tornadus } },
            { "tornadust", new FormInfo { FormName = "therian", Species = Species.Tornadus } },
            { "642t", new FormInfo { FormName = "therian", Species = Species.Thundurus } },
            { "thundurust", new FormInfo { FormName = "therian", Species = Species.Thundurus } },
            { "645t", new FormInfo { FormName = "therian", Species = Species.Landorus } },
            { "landorust", new FormInfo { FormName = "therian", Species = Species.Landorus } },
            { "658a", new FormInfo { FormName = "ash", Species = Species.Greninja } },
            { "greninjaa", new FormInfo { FormName = "ash", Species = Species.Greninja } },
            { "666a", new FormInfo { FormName = "archipelago", Species = Species.Vivillon } },
            { "vivillona", new FormInfo { FormName = "archipelago", Species = Species.Vivillon } },
            { "666c", new FormInfo { FormName = "continental", Species = Species.Vivillon } },
            { "vivillonc", new FormInfo { FormName = "continental", Species = Species.Vivillon } },
            { "666e", new FormInfo { FormName = "elegant", Species = Species.Vivillon } },
            { "vivillone", new FormInfo { FormName = "elegant", Species = Species.Vivillon } },
            { "666f", new FormInfo { FormName = "fancy", Species = Species.Vivillon } },
            { "vivillonf", new FormInfo { FormName = "fancy", Species = Species.Vivillon } },
            { "666g", new FormInfo { FormName = "garden", Species = Species.Vivillon } },
            { "vivillong", new FormInfo { FormName = "garden", Species = Species.Vivillon } },
            { "666h", new FormInfo { FormName = "high plains", Species = Species.Vivillon } },
            { "vivillonh", new FormInfo { FormName = "high plains", Species = Species.Vivillon } },
            { "666i", new FormInfo { FormName = "icy snow", Species = Species.Vivillon } },
            { "vivilloni", new FormInfo { FormName = "icy snow", Species = Species.Vivillon } },
            { "666j", new FormInfo { FormName = "jungle", Species = Species.Vivillon } },
            { "vivillonj", new FormInfo { FormName = "jungle", Species = Species.Vivillon } },
            { "666ma", new FormInfo { FormName = "marine", Species = Species.Vivillon } },
            { "vivillonma", new FormInfo { FormName = "marine", Species = Species.Vivillon } },
            { "666me", new FormInfo { FormName = "meadow", Species = Species.Vivillon } },
            { "vivillonme", new FormInfo { FormName = "meadow", Species = Species.Vivillon } },
            { "666md", new FormInfo { FormName = "modern", Species = Species.Vivillon } },
            { "vivillonmd", new FormInfo { FormName = "modern", Species = Species.Vivillon } },
            { "666ms", new FormInfo { FormName = "monsoon", Species = Species.Vivillon } },
            { "vivillonms", new FormInfo { FormName = "monsoon", Species = Species.Vivillon } },
            { "666o", new FormInfo { FormName = "ocean", Species = Species.Vivillon } },
            { "vivillono", new FormInfo { FormName = "ocean", Species = Species.Vivillon } },
            { "666pb", new FormInfo { FormName = "poké ball", Species = Species.Vivillon } },
            { "vivillonpb", new FormInfo { FormName = "poké ball", Species = Species.Vivillon } },
            { "666po", new FormInfo { FormName = "polar", Species = Species.Vivillon } },
            { "vivillonpo", new FormInfo { FormName = "polar", Species = Species.Vivillon } },
            { "666r", new FormInfo { FormName = "river", Species = Species.Vivillon } },
            { "vivillonr", new FormInfo { FormName = "river", Species = Species.Vivillon } },
            { "666sd", new FormInfo { FormName = "sandstorm", Species = Species.Vivillon } },
            { "vivillonsd", new FormInfo { FormName = "sandstorm", Species = Species.Vivillon } },
            { "666sv", new FormInfo { FormName = "savanna", Species = Species.Vivillon } },
            { "vivillonsv", new FormInfo { FormName = "savanna", Species = Species.Vivillon } },
            { "666su", new FormInfo { FormName = "sun", Species = Species.Vivillon } },
            { "vivillonsu", new FormInfo { FormName = "sun", Species = Species.Vivillon } },
            { "666t", new FormInfo { FormName = "tundra", Species = Species.Vivillon } },
            { "vivillont", new FormInfo { FormName = "tundra", Species = Species.Vivillon } },
            { "669r", new FormInfo { FormName = "red", Species = Species.Flabébé } },
            { "flabébér", new FormInfo { FormName = "red", Species = Species.Flabébé } },
            { "669y", new FormInfo { FormName = "yellow", Species = Species.Flabébé } },
            { "flabébéy", new FormInfo { FormName = "yellow", Species = Species.Flabébé } },
            { "669o", new FormInfo { FormName = "orange", Species = Species.Flabébé } },
            { "flabébéo", new FormInfo { FormName = "orange", Species = Species.Flabébé } },
            { "669b", new FormInfo { FormName = "blue", Species = Species.Flabébé } },
            { "flabébéb", new FormInfo { FormName = "blue", Species = Species.Flabébé } },
            { "669w", new FormInfo { FormName = "white", Species = Species.Flabébé } },
            { "flabébéw", new FormInfo { FormName = "white", Species = Species.Flabébé } },
            { "670r", new FormInfo { FormName = "red", Species = Species.Floette } },
            { "floetter", new FormInfo { FormName = "red", Species = Species.Floette } },
            { "670y", new FormInfo { FormName = "yellow", Species = Species.Floette } },
            { "floettey", new FormInfo { FormName = "yellow", Species = Species.Floette } },
            { "670o", new FormInfo { FormName = "orange", Species = Species.Floette } },
            { "floetteo", new FormInfo { FormName = "orange", Species = Species.Floette } },
            { "670b", new FormInfo { FormName = "blue", Species = Species.Floette } },
            { "floetteb", new FormInfo { FormName = "blue", Species = Species.Floette } },
            { "670w", new FormInfo { FormName = "white", Species = Species.Floette } },
            { "floettew", new FormInfo { FormName = "white", Species = Species.Floette } },
            { "671r", new FormInfo { FormName = "red", Species = Species.Florges } },
            { "florgesr", new FormInfo { FormName = "red", Species = Species.Florges } },
            { "671y", new FormInfo { FormName = "yellow", Species = Species.Florges } },
            { "florgesy", new FormInfo { FormName = "yellow", Species = Species.Florges } },
            { "671o", new FormInfo { FormName = "orange", Species = Species.Florges } },
            { "florgeso", new FormInfo { FormName = "orange", Species = Species.Florges } },
            { "671b", new FormInfo { FormName = "blue", Species = Species.Florges } },
            { "florgesb", new FormInfo { FormName = "blue", Species = Species.Florges } },
            { "671w", new FormInfo { FormName = "white", Species = Species.Florges } },
            { "florgesw", new FormInfo { FormName = "white", Species = Species.Florges } },
            { "678m", new FormInfo { FormName = "male", Species = Species.Meowstic } },
            { "meowsticm", new FormInfo { FormName = "male", Species = Species.Meowstic } },
            { "678f", new FormInfo { FormName = "female", Species = Species.Meowstic } },
            { "meowsticf", new FormInfo { FormName = "female", Species = Species.Meowstic } },
            { "705h", new FormInfo { FormName = "hisui", Species = Species.Sliggoo } },
            { "sliggooh", new FormInfo { FormName = "hisui", Species = Species.Sliggoo } },
            { "706h", new FormInfo { FormName = "hisui", Species = Species.Goodra } },
            { "goodrah", new FormInfo { FormName = "hisui", Species = Species.Goodra } },
            { "710sm", new FormInfo { FormName = "small", Species = Species.Pumpkaboo } },
            { "pumpkaboosm", new FormInfo { FormName = "small", Species = Species.Pumpkaboo } },
            { "710a", new FormInfo { FormName = "average", Species = Species.Pumpkaboo } },
            { "pumpkabooa", new FormInfo { FormName = "average", Species = Species.Pumpkaboo } },
            { "710l", new FormInfo { FormName = "large", Species = Species.Pumpkaboo } },
            { "pumpkabool", new FormInfo { FormName = "large", Species = Species.Pumpkaboo } },
            { "710su", new FormInfo { FormName = "super", Species = Species.Pumpkaboo } },
            { "pumpkaboosu", new FormInfo { FormName = "super", Species = Species.Pumpkaboo } },
            { "711sm", new FormInfo { FormName = "small", Species = Species.Gourgeist } },
            { "gourgeistsm", new FormInfo { FormName = "small", Species = Species.Gourgeist } },
            { "711a", new FormInfo { FormName = "average", Species = Species.Gourgeist } },
            { "gourgeista", new FormInfo { FormName = "average", Species = Species.Gourgeist } },
            { "711l", new FormInfo { FormName = "large", Species = Species.Gourgeist } },
            { "gourgeistl", new FormInfo { FormName = "large", Species = Species.Gourgeist } },
            { "711su", new FormInfo { FormName = "super", Species = Species.Gourgeist } },
            { "gourgeistsu", new FormInfo { FormName = "super", Species = Species.Gourgeist } },
            { "713h", new FormInfo { FormName = "hisui", Species = Species.Avalugg } },
            { "avaluggh", new FormInfo { FormName = "hisui", Species = Species.Avalugg } },
            { "7181", new FormInfo { FormName = "10%", Species = Species.Zygarde } },
            { "zygarde1", new FormInfo { FormName = "10%", Species = Species.Zygarde } },
            { "7181c", new FormInfo { FormName = "10%-c", Species = Species.Zygarde } },
            { "zygarde1c", new FormInfo { FormName = "10%-c", Species = Species.Zygarde } },
            { "7185", new FormInfo { FormName = "50%", Species = Species.Zygarde } },
            { "zygarde5", new FormInfo { FormName = "50%", Species = Species.Zygarde } },
            { "7185c", new FormInfo { FormName = "50%-c", Species = Species.Zygarde } },
            { "zygarde5c", new FormInfo { FormName = "50%-c", Species = Species.Zygarde } },
            { "724h", new FormInfo { FormName = "hisui", Species = Species.Decidueye } },
            { "decidueyeh", new FormInfo { FormName = "hisui", Species = Species.Decidueye } },
            { "735t", new FormInfo { FormName = "totem", Species = Species.Gumshoos } },
            { "gumshoost", new FormInfo { FormName = "totem", Species = Species.Gumshoos } },
            { "738t", new FormInfo { FormName = "totem", Species = Species.Vikavolt } },
            { "vikavoltt", new FormInfo { FormName = "totem", Species = Species.Vikavolt } },
            { "741b", new FormInfo { FormName = "baile", Species = Species.Oricorio } },
            { "oricoriob", new FormInfo { FormName = "baile", Species = Species.Oricorio } },
            { "741po", new FormInfo { FormName = "pom-pom", Species = Species.Oricorio } },
            { "oricoriopo", new FormInfo { FormName = "pom-pom", Species = Species.Oricorio } },
            { "741pa", new FormInfo { FormName = "pa’u", Species = Species.Oricorio } },
            { "oricoriopa", new FormInfo { FormName = "pa’u", Species = Species.Oricorio } },
            { "741s", new FormInfo { FormName = "sensu", Species = Species.Oricorio } },
            { "oricorios", new FormInfo { FormName = "sensu", Species = Species.Oricorio } },
            { "743t", new FormInfo { FormName = "totem", Species = Species.Ribombee } },
            { "ribombeet", new FormInfo { FormName = "totem", Species = Species.Ribombee } },
            { "744d", new FormInfo { FormName = "dusk", Species = Species.Rockruff } },
            { "rockruffd", new FormInfo { FormName = "dusk", Species = Species.Rockruff } },
            { "745md", new FormInfo { FormName = "midday", Species = Species.Lycanroc } },
            { "lycanrocmd", new FormInfo { FormName = "midday", Species = Species.Lycanroc } },
            { "745mn", new FormInfo { FormName = "midnight", Species = Species.Lycanroc } },
            { "lycanrocmn", new FormInfo { FormName = "midnight", Species = Species.Lycanroc } },
            { "745d", new FormInfo { FormName = "dusk", Species = Species.Lycanroc } },
            { "lycanrocd", new FormInfo { FormName = "dusk", Species = Species.Lycanroc } },
            { "752t", new FormInfo { FormName = "totem", Species = Species.Araquanid } },
            { "araquanidt", new FormInfo { FormName = "totem", Species = Species.Araquanid } },
            { "754t", new FormInfo { FormName = "totem", Species = Species.Lurantis } },
            { "lurantist", new FormInfo { FormName = "totem", Species = Species.Lurantis } },
            { "758t", new FormInfo { FormName = "totem", Species = Species.Salazzle } },
            { "salazzlet", new FormInfo { FormName = "totem", Species = Species.Salazzle } },
            { "774r", new FormInfo { FormName = "red", Species = Species.Minior } },
            { "miniorr", new FormInfo { FormName = "red", Species = Species.Minior } },
            { "774o", new FormInfo { FormName = "orange", Species = Species.Minior } },
            { "minioro", new FormInfo { FormName = "orange", Species = Species.Minior } },
            { "774y", new FormInfo { FormName = "yellow", Species = Species.Minior } },
            { "miniory", new FormInfo { FormName = "yellow", Species = Species.Minior } },
            { "774g", new FormInfo { FormName = "green", Species = Species.Minior } },
            { "miniorg", new FormInfo { FormName = "green", Species = Species.Minior } },
            { "774b", new FormInfo { FormName = "blue", Species = Species.Minior } },
            { "miniorb", new FormInfo { FormName = "blue", Species = Species.Minior } },
            { "774i", new FormInfo { FormName = "indigo", Species = Species.Minior } },
            { "miniori", new FormInfo { FormName = "indigo", Species = Species.Minior } },
            { "774v", new FormInfo { FormName = "violet", Species = Species.Minior } },
            { "miniorv", new FormInfo { FormName = "violet", Species = Species.Minior } },
            { "777t", new FormInfo { FormName = "totem", Species = Species.Togedemaru } },
            { "togedemarut", new FormInfo { FormName = "totem", Species = Species.Togedemaru } },
            { "778t", new FormInfo { FormName = "totem", Species = Species.Mimikyu } },
            { "mimikyut", new FormInfo { FormName = "totem", Species = Species.Mimikyu } },
            { "784t", new FormInfo { FormName = "totem", Species = Species.Kommoo } },
            { "kommoot", new FormInfo { FormName = "totem", Species = Species.Kommoo } },
            { "801o", new FormInfo { FormName = "original", Species = Species.Magearna } },
            { "magearnao", new FormInfo { FormName = "original", Species = Species.Magearna } },
            { "849a", new FormInfo { FormName = "amped", Species = Species.Toxtricity } },
            { "toxtricitya", new FormInfo { FormName = "amped", Species = Species.Toxtricity } },
            { "849l", new FormInfo { FormName = "low key", Species = Species.Toxtricity } },
            { "toxtricityl", new FormInfo { FormName = "low key", Species = Species.Toxtricity } },
            { "854p", new FormInfo { FormName = "phony", Species = Species.Sinistea } },
            { "sinisteap", new FormInfo { FormName = "phony", Species = Species.Sinistea } },
            { "854a", new FormInfo { FormName = "antique", Species = Species.Sinistea } },
            { "sinisteaa", new FormInfo { FormName = "antique", Species = Species.Sinistea } },
            { "855p", new FormInfo { FormName = "phony", Species = Species.Polteageist } },
            { "polteageistp", new FormInfo { FormName = "phony", Species = Species.Polteageist } },
            { "855a", new FormInfo { FormName = "antique", Species = Species.Polteageist } },
            { "polteageista", new FormInfo { FormName = "antique", Species = Species.Polteageist } },
            { "876m", new FormInfo { FormName = "male", Species = Species.Indeedee } },
            { "indeedeem", new FormInfo { FormName = "male", Species = Species.Indeedee } },
            { "876f", new FormInfo { FormName = "female", Species = Species.Indeedee } },
            { "indeedeef", new FormInfo { FormName = "female", Species = Species.Indeedee } },
            { "892s", new FormInfo { FormName = "single strike", Species = Species.Urshifu } },
            { "urshifus", new FormInfo { FormName = "single strike", Species = Species.Urshifu } },
            { "892r", new FormInfo { FormName = "rapid strike", Species = Species.Urshifu } },
            { "urshifur", new FormInfo { FormName = "rapid strike", Species = Species.Urshifu } },
            { "893d", new FormInfo { FormName = "dada", Species = Species.Zarude } },
            { "zaruded", new FormInfo { FormName = "dada", Species = Species.Zarude } },
            { "902m", new FormInfo { FormName = "male", Species = Species.Basculegion } },
            { "basculegionm", new FormInfo { FormName = "male", Species = Species.Basculegion } },
            { "902f", new FormInfo { FormName = "female", Species = Species.Basculegion } },
            { "basculegionf", new FormInfo { FormName = "female", Species = Species.Basculegion } },
            { "905t", new FormInfo { FormName = "therian", Species = Species.Enamorus } },
            { "enamorust", new FormInfo { FormName = "therian", Species = Species.Enamorus } },
            { "8691", new FormInfo { FormName = "vanilla cream strawberry", Species = Species.Alcremie } },
            { "alcremie1", new FormInfo { FormName = "vanilla cream strawberry", Species = Species.Alcremie } },
            { "8692", new FormInfo { FormName = "vanilla cream berry", Species = Species.Alcremie } },
            { "alcremie2", new FormInfo { FormName = "vanilla cream berry", Species = Species.Alcremie } },
            { "8693", new FormInfo { FormName = "vanilla cream love", Species = Species.Alcremie } },
            { "alcremie3", new FormInfo { FormName = "vanilla cream love", Species = Species.Alcremie } },
            { "8694", new FormInfo { FormName = "vanilla cream star", Species = Species.Alcremie } },
            { "alcremie4", new FormInfo { FormName = "vanilla cream star", Species = Species.Alcremie } },
            { "8695", new FormInfo { FormName = "vanilla cream clover", Species = Species.Alcremie } },
            { "alcremie5", new FormInfo { FormName = "vanilla cream clover", Species = Species.Alcremie } },
            { "8696", new FormInfo { FormName = "vanilla cream flower", Species = Species.Alcremie } },
            { "alcremie6", new FormInfo { FormName = "vanilla cream flower", Species = Species.Alcremie } },
            { "8697", new FormInfo { FormName = "vanilla cream ribbon", Species = Species.Alcremie } },
            { "alcremie7", new FormInfo { FormName = "vanilla cream ribbon", Species = Species.Alcremie } },
            { "8698", new FormInfo { FormName = "ruby cream strawberry", Species = Species.Alcremie } },
            { "alcremie8", new FormInfo { FormName = "ruby cream strawberry", Species = Species.Alcremie } },
            { "8699", new FormInfo { FormName = "ruby cream berry", Species = Species.Alcremie } },
            { "alcremie9", new FormInfo { FormName = "ruby cream berry", Species = Species.Alcremie } },
            { "86910", new FormInfo { FormName = "ruby cream love", Species = Species.Alcremie } },
            { "alcremie10", new FormInfo { FormName = "ruby cream love", Species = Species.Alcremie } },
            { "86911", new FormInfo { FormName = "ruby cream star", Species = Species.Alcremie } },
            { "alcremie11", new FormInfo { FormName = "ruby cream star", Species = Species.Alcremie } },
            { "86912", new FormInfo { FormName = "ruby cream clover", Species = Species.Alcremie } },
            { "alcremie12", new FormInfo { FormName = "ruby cream clover", Species = Species.Alcremie } },
            { "86913", new FormInfo { FormName = "ruby cream flower", Species = Species.Alcremie } },
            { "alcremie13", new FormInfo { FormName = "ruby cream flower", Species = Species.Alcremie } },
            { "86914", new FormInfo { FormName = "ruby cream ribbon", Species = Species.Alcremie } },
            { "alcremie14", new FormInfo { FormName = "ruby cream ribbon", Species = Species.Alcremie } },
            { "86915", new FormInfo { FormName = "matcha cream strawberry", Species = Species.Alcremie } },
            { "alcremie15", new FormInfo { FormName = "matcha cream strawberry", Species = Species.Alcremie } },
            { "86916", new FormInfo { FormName = "matcha cream berry", Species = Species.Alcremie } },
            { "alcremie16", new FormInfo { FormName = "matcha cream berry", Species = Species.Alcremie } },
            { "86917", new FormInfo { FormName = "matcha cream love", Species = Species.Alcremie } },
            { "alcremie17", new FormInfo { FormName = "matcha cream love", Species = Species.Alcremie } },
            { "86918", new FormInfo { FormName = "matcha cream star", Species = Species.Alcremie } },
            { "alcremie18", new FormInfo { FormName = "matcha cream star", Species = Species.Alcremie } },
            { "86919", new FormInfo { FormName = "matcha cream clover", Species = Species.Alcremie } },
            { "alcremie19", new FormInfo { FormName = "matcha cream clover", Species = Species.Alcremie } },
            { "86920", new FormInfo { FormName = "matcha cream flower", Species = Species.Alcremie } },
            { "alcremie20", new FormInfo { FormName = "matcha cream flower", Species = Species.Alcremie } },
            { "86921", new FormInfo { FormName = "matcha cream ribbon", Species = Species.Alcremie } },
            { "alcremie21", new FormInfo { FormName = "matcha cream ribbon", Species = Species.Alcremie } },
            { "86922", new FormInfo { FormName = "mint cream strawberry", Species = Species.Alcremie } },
            { "alcremie22", new FormInfo { FormName = "mint cream strawberry", Species = Species.Alcremie } },
            { "86923", new FormInfo { FormName = "mint cream berry", Species = Species.Alcremie } },
            { "alcremie23", new FormInfo { FormName = "mint cream berry", Species = Species.Alcremie } },
            { "86924", new FormInfo { FormName = "mint cream love", Species = Species.Alcremie } },
            { "alcremie24", new FormInfo { FormName = "mint cream love", Species = Species.Alcremie } },
            { "86925", new FormInfo { FormName = "mint cream star", Species = Species.Alcremie } },
            { "alcremie25", new FormInfo { FormName = "mint cream star", Species = Species.Alcremie } },
            { "86926", new FormInfo { FormName = "mint cream clover", Species = Species.Alcremie } },
            { "alcremie26", new FormInfo { FormName = "mint cream clover", Species = Species.Alcremie } },
            { "86927", new FormInfo { FormName = "mint cream flower", Species = Species.Alcremie } },
            { "alcremie27", new FormInfo { FormName = "mint cream flower", Species = Species.Alcremie } },
            { "86928", new FormInfo { FormName = "mint cream ribbon", Species = Species.Alcremie } },
            { "alcremie28", new FormInfo { FormName = "mint cream ribbon", Species = Species.Alcremie } },
            { "86929", new FormInfo { FormName = "lemon cream strawberry", Species = Species.Alcremie } },
            { "alcremie29", new FormInfo { FormName = "lemon cream strawberry", Species = Species.Alcremie } },
            { "86930", new FormInfo { FormName = "lemon cream berry", Species = Species.Alcremie } },
            { "alcremie30", new FormInfo { FormName = "lemon cream berry", Species = Species.Alcremie } },
            { "86931", new FormInfo { FormName = "lemon cream love", Species = Species.Alcremie } },
            { "alcremie31", new FormInfo { FormName = "lemon cream love", Species = Species.Alcremie } },
            { "86932", new FormInfo { FormName = "lemon cream star", Species = Species.Alcremie } },
            { "alcremie32", new FormInfo { FormName = "lemon cream star", Species = Species.Alcremie } },
            { "86933", new FormInfo { FormName = "lemon cream clover", Species = Species.Alcremie } },
            { "alcremie33", new FormInfo { FormName = "lemon cream clover", Species = Species.Alcremie } },
            { "86934", new FormInfo { FormName = "lemon cream flower", Species = Species.Alcremie } },
            { "alcremie34", new FormInfo { FormName = "lemon cream flower", Species = Species.Alcremie } },
            { "86935", new FormInfo { FormName = "lemon cream ribbon", Species = Species.Alcremie } },
            { "alcremie35", new FormInfo { FormName = "lemon cream ribbon", Species = Species.Alcremie } },
            { "86936", new FormInfo { FormName = "salted cream strawberry", Species = Species.Alcremie } },
            { "alcremie36", new FormInfo { FormName = "salted cream strawberry", Species = Species.Alcremie } },
            { "86937", new FormInfo { FormName = "salted cream berry", Species = Species.Alcremie } },
            { "alcremie37", new FormInfo { FormName = "salted cream berry", Species = Species.Alcremie } },
            { "86938", new FormInfo { FormName = "salted cream love", Species = Species.Alcremie } },
            { "alcremie38", new FormInfo { FormName = "salted cream love", Species = Species.Alcremie } },
            { "86939", new FormInfo { FormName = "salted cream star", Species = Species.Alcremie } },
            { "alcremie39", new FormInfo { FormName = "salted cream star", Species = Species.Alcremie } },
            { "86940", new FormInfo { FormName = "salted cream clover", Species = Species.Alcremie } },
            { "alcremie40", new FormInfo { FormName = "salted cream clover", Species = Species.Alcremie } },
            { "86941", new FormInfo { FormName = "salted cream flower", Species = Species.Alcremie } },
            { "alcremie41", new FormInfo { FormName = "salted cream flower", Species = Species.Alcremie } },
            { "86942", new FormInfo { FormName = "salted cream ribbon", Species = Species.Alcremie } },
            { "alcremie42", new FormInfo { FormName = "salted cream ribbon", Species = Species.Alcremie } },
            { "86943", new FormInfo { FormName = "ruby swirl strawberry", Species = Species.Alcremie } },
            { "alcremie43", new FormInfo { FormName = "ruby swirl strawberry", Species = Species.Alcremie } },
            { "86944", new FormInfo { FormName = "ruby swirl berry", Species = Species.Alcremie } },
            { "alcremie44", new FormInfo { FormName = "ruby swirl berry", Species = Species.Alcremie } },
            { "86945", new FormInfo { FormName = "ruby swirl love", Species = Species.Alcremie } },
            { "alcremie45", new FormInfo { FormName = "ruby swirl love", Species = Species.Alcremie } },
            { "86946", new FormInfo { FormName = "ruby swirl star", Species = Species.Alcremie } },
            { "alcremie46", new FormInfo { FormName = "ruby swirl star", Species = Species.Alcremie } },
            { "86947", new FormInfo { FormName = "ruby swirl clover", Species = Species.Alcremie } },
            { "alcremie47", new FormInfo { FormName = "ruby swirl clover", Species = Species.Alcremie } },
            { "86948", new FormInfo { FormName = "ruby swirl flower", Species = Species.Alcremie } },
            { "alcremie48", new FormInfo { FormName = "ruby swirl flower", Species = Species.Alcremie } },
            { "86949", new FormInfo { FormName = "ruby swirl ribbon", Species = Species.Alcremie } },
            { "alcremie49", new FormInfo { FormName = "ruby swirl ribbon", Species = Species.Alcremie } },
            { "86950", new FormInfo { FormName = "caramel swirl strawberry", Species = Species.Alcremie } },
            { "alcremie50", new FormInfo { FormName = "caramel swirl strawberry", Species = Species.Alcremie } },
            { "86951", new FormInfo { FormName = "caramel swirl berry", Species = Species.Alcremie } },
            { "alcremie51", new FormInfo { FormName = "caramel swirl berry", Species = Species.Alcremie } },
            { "86952", new FormInfo { FormName = "caramel swirl love", Species = Species.Alcremie } },
            { "alcremie52", new FormInfo { FormName = "caramel swirl love", Species = Species.Alcremie } },
            { "86953", new FormInfo { FormName = "caramel swirl star", Species = Species.Alcremie } },
            { "alcremie53", new FormInfo { FormName = "caramel swirl star", Species = Species.Alcremie } },
            { "86954", new FormInfo { FormName = "caramel swirl clover", Species = Species.Alcremie } },
            { "alcremie54", new FormInfo { FormName = "caramel swirl clover", Species = Species.Alcremie } },
            { "86955", new FormInfo { FormName = "caramel swirl flower", Species = Species.Alcremie } },
            { "alcremie55", new FormInfo { FormName = "caramel swirl flower", Species = Species.Alcremie } },
            { "86956", new FormInfo { FormName = "caramel swirl ribbon", Species = Species.Alcremie } },
            { "alcremie56", new FormInfo { FormName = "caramel swirl ribbon", Species = Species.Alcremie } },
            { "86957", new FormInfo { FormName = "rainbow swirl strawberry", Species = Species.Alcremie } },
            { "alcremie57", new FormInfo { FormName = "rainbow swirl strawberry", Species = Species.Alcremie } },
            { "86958", new FormInfo { FormName = "rainbow swirl berry", Species = Species.Alcremie } },
            { "alcremie58", new FormInfo { FormName = "rainbow swirl berry", Species = Species.Alcremie } },
            { "86959", new FormInfo { FormName = "rainbow swirl love", Species = Species.Alcremie } },
            { "alcremie59", new FormInfo { FormName = "rainbow swirl love", Species = Species.Alcremie } },
            { "86960", new FormInfo { FormName = "rainbow swirl star", Species = Species.Alcremie } },
            { "alcremie60", new FormInfo { FormName = "rainbow swirl star", Species = Species.Alcremie } },
            { "86961", new FormInfo { FormName = "rainbow swirl clover", Species = Species.Alcremie } },
            { "alcremie61", new FormInfo { FormName = "rainbow swirl clover", Species = Species.Alcremie } },
            { "86962", new FormInfo { FormName = "rainbow swirl flower", Species = Species.Alcremie } },
            { "alcremie62", new FormInfo { FormName = "rainbow swirl flower", Species = Species.Alcremie } },
            { "86963", new FormInfo { FormName = "rainbow swirl ribbon", Species = Species.Alcremie } },
            { "alcremie63", new FormInfo { FormName = "rainbow swirl ribbon", Species = Species.Alcremie } },
        };
    }
}
