using PKHeX.Core;
using System;
using System.Collections.Generic;
using System.IO;

namespace Chatbot_TextStrings
{
    public static class YT_Forms
    {
        public class FormIdentifier
        {
            public bool Valid { get; set; }
            public string FormFileName { get; set; }
            public int FormID { get; set; }
            public PKM? PK { get; set; }
        }

        /// <summary>
        /// Returns the Form Identifier and the Species Name.
        /// </summary>
        /// <param name="Nickname">Nicknamed Pokemon from User</param>
        /// <returns>Formated Nickname Identifier and PKHEX Formated Species Name</returns>
        public static FormIdentifier GetFormIdentifier(int game, int species, string Nickname)
        {
            try
            {
                string FolderName = "";
                string Extension = "";
                string FormFile = "";

                switch (game)
                {
                    case 6:
                        FolderName = "Pokemon6";
                        Extension = "pk6";
                        break;
                    case 7:
                    case 88:
                        FolderName = "Pokemon";
                        Extension = "pk7";
                        break;
                    case 8:
                        FolderName = "Pokemon8";
                        Extension = "pk8";
                        break;
                    case 888:
                        FolderName = "Pokemon8a";
                        Extension = "pa8";
                        break;
                    default:
                        break;
                }

                bool containsDigitForm = int.TryParse(Nickname[..1], out int _);

                if (!Nickname.StartsWith(((Species)species).ToString(), System.StringComparison.OrdinalIgnoreCase) && (Species)species is not Species.None && !containsDigitForm)
                    Nickname = (Species)species + Nickname;


                FormFile = $"C:\\{FolderName}\\{(Species)species}\\{NicknameForms[Nickname.ToLower()]}.{Extension}";
                Console.WriteLine("Form File: " + FormFile);

                PKM? pk = EntityFormat.GetFromBytes(File.ReadAllBytes(FormFile));
                if (pk != null)
                {
                    return new FormIdentifier()
                    {
                        Valid = true,
                        FormFileName = Path.GetFileName(FormFile).Replace($".{Extension}", ""),
                        PK = pk,
                        FormID = pk.Form
                    };
                }
                return new FormIdentifier()
                {
                    Valid = false,
                    FormFileName = String.Empty,
                    PK = null,
                    FormID = -1
                };
            }

            catch (Exception ex)
            {
                Console.WriteLine("Exception: " + ex.ToString());
                return new FormIdentifier()
                {
                    Valid = false,
                    FormFileName = String.Empty,
                    PK = null,
                    FormID = -1
                };
            }
        }

        private static string GetDict(string key)
        {
            try
            {
                return NicknameForms[key];
            }
            catch { return string.Empty; }
        }

        private readonly static Dictionary<string, string> NicknameForms = new()
        {
            { "19a", "alola" },
            { "rattataa", "alola" },
            { "20a", "alola" },
            { "raticatea", "alola" },
            { "20t", "totem" },
            { "raticatet", "totem" },
            { "25o", "original" },
            { "pikachuo", "original" },
            { "25h", "hoenn" },
            { "pikachuh", "hoenn" },
            { "25s", "sinnoh" },
            { "pikachus", "sinnoh" },
            { "25u", "unova" },
            { "pikachuu", "unova" },
            { "25k", "kalos" },
            { "pikachuk", "kalos" },
            { "25a", "alola" },
            { "pikachua", "alola" },
            { "25p", "partner" },
            { "pikachup", "partner" },
            { "25w", "world" },
            { "pikachuw", "world" },
            { "26a", "alola" },
            { "raichua", "alola" },
            { "27a", "alola" },
            { "sandshrewa", "alola" },
            { "28a", "alola" },
            { "sandslasha", "alola" },
            { "37a", "alola" },
            { "vulpixa", "alola" },
            { "38a", "alola" },
            { "ninetalesa", "alola" },
            { "50a", "alola" },
            { "digletta", "alola" },
            { "51a", "alola" },
            { "dugtrioa", "alola" },
            { "52a", "alola" },
            { "meowtha", "alola" },
            { "52g", "galar" },
            { "meowthg", "galar" },
            { "53a", "alola" },
            { "persiana", "alola" },
            { "58h", "hisui" },
            { "growlitheh", "hisui" },
            { "59h", "hisui" },
            { "arcanineh", "hisui" },
            { "74a", "alola" },
            { "geodudea", "alola" },
            { "75a", "alola" },
            { "gravelera", "alola" },
            { "76a", "alola" },
            { "golema", "alola" },
            { "77g", "galar" },
            { "ponytag", "galar" },
            { "78g", "galar" },
            { "rapidashg", "galar" },
            { "79g", "galar" },
            { "slowpokeg", "galar" },
            { "80g", "galar" },
            { "slowbrog", "galar" },
            { "83g", "galar" },
            { "farfetchdg", "galar" },
            { "88a", "alola" },
            { "grimera", "alola" },
            { "89a", "alola" },
            { "muka", "alola" },
            { "100h", "hisui" },
            { "voltorbh", "hisui" },
            { "101h", "hisui" },
            { "electrodeh", "hisui" },
            { "103a", "alola" },
            { "exeggutora", "alola" },
            { "105a", "alola" },
            { "marowaka", "alola" },
            { "105t", "totem" },
            { "marowakt", "totem" },
            { "110g", "galar" },
            { "weezingg", "galar" },
            { "122g", "galar" },
            { "mrmimeg", "galar" },
            { "144g", "galar" },
            { "articunog", "galar" },
            { "145g", "galar" },
            { "zapdosg", "galar" },
            { "146g", "galar" },
            { "moltresg", "galar" },
            { "157h", "hisui" },
            { "typhlosionh", "hisui" },
            { "199g", "galar" },
            { "slowkingg", "galar" },
            { "201a", "a" },
            { "unowna", "a" },
            { "201b", "b" },
            { "unownb", "b" },
            { "201c", "c" },
            { "unownc", "c" },
            { "201d", "d" },
            { "unownd", "d" },
            { "201e", "e" },
            { "unowne", "e" },
            { "201f", "f" },
            { "unownf", "f" },
            { "201g", "g" },
            { "unowng", "g" },
            { "201h", "h" },
            { "unownh", "h" },
            { "201i", "i" },
            { "unowni", "i" },
            { "201j", "j" },
            { "unownj", "j" },
            { "201k", "k" },
            { "unownk", "k" },
            { "201l", "l" },
            { "unownl", "l" },
            { "201m", "m" },
            { "unownm", "m" },
            { "201n", "n" },
            { "unownn", "n" },
            { "201o", "o" },
            { "unowno", "o" },
            { "201p", "p" },
            { "unownp", "p" },
            { "201q", "q" },
            { "unownq", "q" },
            { "201r", "r" },
            { "unownr", "r" },
            { "201s", "s" },
            { "unowns", "s" },
            { "201t", "t" },
            { "unownt", "t" },
            { "201u", "u" },
            { "unownu", "u" },
            { "201v", "v" },
            { "unownv", "v" },
            { "201w", "w" },
            { "unownw", "w" },
            { "201x", "x" },
            { "unownx", "x" },
            { "201y", "y" },
            { "unowny", "y" },
            { "201z", "z" },
            { "unownz", "z" },
            { "201?", "?" },
            { "unown?", "?" },
            { "201!", "!" },
            { "unown!", "!" },
            { "211h", "hisui" },
            { "qwilfishh", "hisui" },
            { "215h", "hisui" },
            { "sneaselh", "hisui" },
            { "222g", "galar" },
            { "corsolag", "galar" },
            { "263g", "galar" },
            { "zigzagoong", "galar" },
            { "264g", "galar" },
            { "linooneg", "galar" },
            { "386a", "attack" },
            { "deoxysa", "attack" },
            { "386d", "defense" },
            { "deoxysd", "defense" },
            { "386s", "speed" },
            { "deoxyss", "speed" },
            { "412p", "plant" },
            { "burmyp", "plant" },
            { "412s", "sandy" },
            { "burmys", "sandy" },
            { "412t", "trash" },
            { "burmyt", "trash" },
            { "413p", "plant" },
            { "wormadamp", "plant" },
            { "413s", "sandy" },
            { "wormadams", "sandy" },
            { "413t", "trash" },
            { "wormadamt", "trash" },
            { "422e", "east" },
            { "shellose", "east" },
            { "422w", "west" },
            { "shellosw", "west" },
            { "423e", "east" },
            { "gastrodone", "east" },
            { "423w", "west" },
            { "gastrodonw", "west" },
            { "479h", "heat" },
            { "rotomh", "heat" },
            { "479w", "wash" },
            { "rotomw", "wash" },
            { "479fr", "frost" },
            { "rotomfr", "frost" },
            { "479fa", "fan" },
            { "rotomfa", "fan" },
            { "479m", "mow" },
            { "rotomm", "mow" },
            { "483o", "origin" },
            { "dialgao", "origin" },
            { "484o", "origin" },
            { "palkiao", "origin" },
            { "487o", "origin" },
            { "giratinao", "origin" },
            { "493n", "normal" },
            { "arceusn", "normal" },
            { "493fe", "fire" },
            { "arceusfe", "fire" },
            { "493w", "water" },
            { "arceusw", "water" },
            { "493e", "electric" },
            { "arceuse", "electric" },
            { "493gs", "grass" },
            { "arceusgs", "grass" },
            { "493i", "ice" },
            { "arceusi", "ice" },
            { "493ft", "fighting" },
            { "arceusft", "fighting" },
            { "493po", "poison" },
            { "arceuspo", "poison" },
            { "493gd", "ground" },
            { "arceusgd", "ground" },
            { "493fl", "flying" },
            { "arceusfl", "flying" },
            { "493ps", "psychic" },
            { "arceusps", "psychic" },
            { "493b", "bug" },
            { "arceusb", "bug" },
            { "493r", "rock" },
            { "arceusr", "rock" },
            { "493gt", "ghost" },
            { "arceusgt", "ghost" },
            { "493dr", "dragon" },
            { "arceusdr", "dragon" },
            { "493da", "dark" },
            { "arceusda", "dark" },
            { "493s", "steel" },
            { "arceuss", "steel" },
            { "493fa", "fairy" },
            { "arceusfa", "fairy" },
            { "493l", "legend" },
            { "arceusl", "legend" },
            { "503h", "hisui" },
            { "samurotth", "hisui" },
            { "549h", "hisui" },
            { "lilliganth", "hisui" },
            { "550r", "red" },
            { "basculinr", "red" },
            { "550b", "blue" },
            { "basculinb", "blue" },
            { "550w", "white" },
            { "basculinw", "white" },
            { "554g", "galar" },
            { "darumakag", "galar" },
            { "555g", "galar" },
            { "darmanitang", "galar" },
            { "562g", "galar" },
            { "yamaskg", "galar" },
            { "570h", "hisui" },
            { "zoruah", "hisui" },
            { "571h", "hisui" },
            { "zoroarkh", "hisui" },
            { "585sp", "spring" },
            { "deerlingsp", "spring" },
            { "585su", "summer" },
            { "deerlingsu", "summer" },
            { "585a", "autumn" },
            { "deerlinga", "autumn" },
            { "585w", "winter" },
            { "deerlingw", "winter" },
            { "586sp", "spring" },
            { "sawsbucksp", "spring" },
            { "586su", "summer" },
            { "sawsbucksu", "summer" },
            { "586a", "autumn" },
            { "sawsbucka", "autumn" },
            { "586w", "winter" },
            { "sawsbuckw", "winter" },
            { "618g", "galar" },
            { "stunfiskg", "galar" },
            { "628h", "hisui" },
            { "braviaryh", "hisui" },
            { "641t", "therian" },
            { "tornadust", "therian" },
            { "642t", "therian" },
            { "thundurust", "therian" },
            { "645t", "therian" },
            { "landorust", "therian" },
            { "658a", "ash" },
            { "greninjaa", "ash" },
            { "666a", "archipelago" },
            { "vivillona", "archipelago" },
            { "666c", "continental" },
            { "vivillonc", "continental" },
            { "666e", "elegant" },
            { "vivillone", "elegant" },
            { "666f", "fancy" },
            { "vivillonf", "fancy" },
            { "666g", "garden" },
            { "vivillong", "garden" },
            { "666h", "high plains" },
            { "vivillonh", "high plains" },
            { "666i", "icy snow " },
            { "vivilloni", "icy snow " },
            { "666j", "jungle " },
            { "vivillonj", "jungle " },
            { "666ma", "marine " },
            { "vivillonma", "marine " },
            { "666me", "meadow " },
            { "vivillonme", "meadow " },
            { "666md", "modern " },
            { "vivillonmd", "modern " },
            { "666ms", "monsoon " },
            { "vivillonms", "monsoon " },
            { "666o", "ocean " },
            { "vivillono", "ocean " },
            { "666pb", "poké ball" },
            { "vivillonpb", "poké ball" },
            { "666po", "polar " },
            { "vivillonpo", "polar " },
            { "666r", "river " },
            { "vivillonr", "river " },
            { "666sd", "sandstorm " },
            { "vivillonsd", "sandstorm " },
            { "666sv", "savanna " },
            { "vivillonsv", "savanna " },
            { "666su", "sun " },
            { "vivillonsu", "sun " },
            { "666t", "tundra" },
            { "vivillont", "tundra" },
            { "669r", "red" },
            { "flabébér", "red" },
            { "669y", "yellow" },
            { "flabébéy", "yellow" },
            { "669o", "orange" },
            { "flabébéo", "orange" },
            { "669b", "blue" },
            { "flabébéb", "blue" },
            { "669w", "white" },
            { "flabébéw", "white" },
            { "670r", "red" },
            { "floetter", "red" },
            { "670y", "yellow" },
            { "floettey", "yellow" },
            { "670o", "orange" },
            { "floetteo", "orange" },
            { "670b", "blue" },
            { "floetteb", "blue" },
            { "670w", "white" },
            { "floettew", "white" },
            { "671r", "red" },
            { "florgesr", "red" },
            { "671y", "yellow" },
            { "florgesy", "yellow" },
            { "671o", "orange" },
            { "florgeso", "orange" },
            { "671b", "blue" },
            { "florgesb", "blue" },
            { "671w", "white" },
            { "florgesw", "white" },
            { "678m", "male" },
            { "meowsticm", "male" },
            { "678f", "female" },
            { "meowsticf", "female" },
            { "705h", "hisui" },
            { "sliggooh", "hisui" },
            { "706h", "hisui" },
            { "goodrah", "hisui" },
            { "710sm", "small" },
            { "pumpkaboosm", "small" },
            { "710a", "average" },
            { "pumpkabooa", "average" },
            { "710l", "large" },
            { "pumpkabool", "large" },
            { "710su", "super" },
            { "pumpkaboosu", "super" },
            { "711sm", "small" },
            { "gourgeistsm", "small" },
            { "711a", "average" },
            { "gourgeista", "average" },
            { "711l", "large" },
            { "gourgeistl", "large" },
            { "711su", "super" },
            { "gourgeistsu", "super" },
            { "713h", "hisui" },
            { "avaluggh", "hisui" },
            { "7181", "10%" },
            { "zygarde1", "10%" },
            { "7181c", "10%-c" },
            { "zygarde1c", "10%-c" },
            { "7185", "50%" },
            { "zygarde5", "50%" },
            { "7185c", "50%-c" },
            { "zygarde5c", "50%-c" },
            { "724h", "hisui" },
            { "decidueyeh", "hisui" },
            { "735t", "totem" },
            { "gumshoost", "totem" },
            { "738t", "totem" },
            { "vikavoltt", "totem" },
            { "741b", "baile" },
            { "oricoriob", "baile" },
            { "741po", "pom-pom" },
            { "oricoriopo", "pom-pom" },
            { "741pa", "pa’u" },
            { "oricoriopa", "pa’u" },
            { "741s", "sensu" },
            { "oricorios", "sensu" },
            { "743t", "totem" },
            { "ribombeet", "totem" },
            { "744d", "dusk" },
            { "rockruffd", "dusk" },
            { "745md", "midday" },
            { "lycanrocmd", "midday" },
            { "745mn", "midnight" },
            { "lycanrocmn", "midnight" },
            { "745d", "dusk" },
            { "lycanrocd", "dusk" },
            { "752t", "totem" },
            { "araquanidt", "totem" },
            { "754t", "totem" },
            { "lurantist", "totem" },
            { "758t", "totem" },
            { "salazzlet", "totem" },
            { "774r", "red" },
            { "miniorr", "red" },
            { "774o", "orange" },
            { "minioro", "orange" },
            { "774y", "yellow" },
            { "miniory", "yellow" },
            { "774g", "green" },
            { "miniorg", "green" },
            { "774b", "blue" },
            { "miniorb", "blue" },
            { "774i", "indigo" },
            { "miniori", "indigo" },
            { "774v", "violet" },
            { "miniorv", "violet" },
            { "777t", "totem" },
            { "togedemarut", "totem" },
            { "778t", "totem" },
            { "mimikyut", "totem" },
            { "784t", "totem" },
            { "kommoot", "totem" },
            { "801o", "original" },
            { "magearnao", "original" },
            { "849a", "amped" },
            { "toxtricitya", "amped" },
            { "849l", "low key" },
            { "toxtricityl", "low key" },
            { "854p", "phony" },
            { "sinisteap", "phony" },
            { "854a", "antique" },
            { "sinisteaa", "antique" },
            { "855p", "phony" },
            { "polteageistp", "phony" },
            { "855a", "antique" },
            { "polteageista", "antique" },
            { "876m", "male" },
            { "indeedeem", "male" },
            { "876f", "female" },
            { "indeedeef", "female" },
            { "892s", "single strike" },
            { "urshifus", "single strike" },
            { "892r", "rapid strike" },
            { "urshifur", "rapid strike" },
            { "893d", "dada" },
            { "zaruded", "dada" },
            { "902m", "male" },
            { "basculegionm", "male" },
            { "902f", "female" },
            { "basculegionf", "female" },
            { "905t", "therian" },
            { "enamorust", "therian" },
            { "8691", "vanilla cream strawberry" },
            { "alcremie1", "vanilla cream strawberry" },
            { "8692", "vanilla cream berry" },
            { "alcremie2", "vanilla cream berry" },
            { "8693", "vanilla cream love" },
            { "alcremie3", "vanilla cream love" },
            { "8694", "vanilla cream star" },
            { "alcremie4", "vanilla cream star" },
            { "8695", "vanilla cream clover" },
            { "alcremie5", "vanilla cream clover" },
            { "8696", "vanilla cream flower" },
            { "alcremie6", "vanilla cream flower" },
            { "8697", "vanilla cream ribbon" },
            { "alcremie7", "vanilla cream ribbon" },
            { "8698", "ruby cream strawberry" },
            { "alcremie8", "ruby cream strawberry" },
            { "8699", "ruby cream berry" },
            { "alcremie9", "ruby cream berry" },
            { "86910", "ruby cream love" },
            { "alcremie10", "ruby cream love" },
            { "86911", "ruby cream star" },
            { "alcremie11", "ruby cream star" },
            { "86912", "ruby cream clover" },
            { "alcremie12", "ruby cream clover" },
            { "86913", "ruby cream flower" },
            { "alcremie13", "ruby cream flower" },
            { "86914", "ruby cream ribbon" },
            { "alcremie14", "ruby cream ribbon" },
            { "86915", "matcha cream strawberry" },
            { "alcremie15", "matcha cream strawberry" },
            { "86916", "matcha cream berry" },
            { "alcremie16", "matcha cream berry" },
            { "86917", "matcha cream love" },
            { "alcremie17", "matcha cream love" },
            { "86918", "matcha cream star" },
            { "alcremie18", "matcha cream star" },
            { "86919", "matcha cream clover" },
            { "alcremie19", "matcha cream clover" },
            { "86920", "matcha cream flower" },
            { "alcremie20", "matcha cream flower" },
            { "86921", "matcha cream ribbon" },
            { "alcremie21", "matcha cream ribbon" },
            { "86922", "mint cream strawberry" },
            { "alcremie22", "mint cream strawberry" },
            { "86923", "mint cream berry" },
            { "alcremie23", "mint cream berry" },
            { "86924", "mint cream love" },
            { "alcremie24", "mint cream love" },
            { "86925", "mint cream star" },
            { "alcremie25", "mint cream star" },
            { "86926", "mint cream clover" },
            { "alcremie26", "mint cream clover" },
            { "86927", "mint cream flower" },
            { "alcremie27", "mint cream flower" },
            { "86928", "mint cream ribbon" },
            { "alcremie28", "mint cream ribbon" },
            { "86929", "lemon cream strawberry" },
            { "alcremie29", "lemon cream strawberry" },
            { "86930", "lemon cream berry" },
            { "alcremie30", "lemon cream berry" },
            { "86931", "lemon cream love" },
            { "alcremie31", "lemon cream love" },
            { "86932", "lemon cream star" },
            { "alcremie32", "lemon cream star" },
            { "86933", "lemon cream clover" },
            { "alcremie33", "lemon cream clover" },
            { "86934", "lemon cream flower" },
            { "alcremie34", "lemon cream flower" },
            { "86935", "lemon cream ribbon" },
            { "alcremie35", "lemon cream ribbon" },
            { "86936", "salted cream strawberry" },
            { "alcremie36", "salted cream strawberry" },
            { "86937", "salted cream berry" },
            { "alcremie37", "salted cream berry" },
            { "86938", "salted cream love" },
            { "alcremie38", "salted cream love" },
            { "86939", "salted cream star" },
            { "alcremie39", "salted cream star" },
            { "86940", "salted cream clover" },
            { "alcremie40", "salted cream clover" },
            { "86941", "salted cream flower" },
            { "alcremie41", "salted cream flower" },
            { "86942", "salted cream ribbon" },
            { "alcremie42", "salted cream ribbon" },
            { "86943", "ruby swirl strawberry" },
            { "alcremie43", "ruby swirl strawberry" },
            { "86944", "ruby swirl berry" },
            { "alcremie44", "ruby swirl berry" },
            { "86945", "ruby swirl love" },
            { "alcremie45", "ruby swirl love" },
            { "86946", "ruby swirl star" },
            { "alcremie46", "ruby swirl star" },
            { "86947", "ruby swirl clover" },
            { "alcremie47", "ruby swirl clover" },
            { "86948", "ruby swirl flower" },
            { "alcremie48", "ruby swirl flower" },
            { "86949", "ruby swirl ribbon" },
            { "alcremie49", "ruby swirl ribbon" },
            { "86950", "caramel swirl strawberry" },
            { "alcremie50", "caramel swirl strawberry" },
            { "86951", "caramel swirl berry" },
            { "alcremie51", "caramel swirl berry" },
            { "86952", "caramel swirl love" },
            { "alcremie52", "caramel swirl love" },
            { "86953", "caramel swirl star" },
            { "alcremie53", "caramel swirl star" },
            { "86954", "caramel swirl clover" },
            { "alcremie54", "caramel swirl clover" },
            { "86955", "caramel swirl flower" },
            { "alcremie55", "caramel swirl flower" },
            { "86956", "caramel swirl ribbon" },
            { "alcremie56", "caramel swirl ribbon" },
            { "86957", "rainbow swirl strawberry" },
            { "alcremie57", "rainbow swirl strawberry" },
            { "86958", "rainbow swirl berry" },
            { "alcremie58", "rainbow swirl berry" },
            { "86959", "rainbow swirl love" },
            { "alcremie59", "rainbow swirl love" },
            { "86960", "rainbow swirl star" },
            { "alcremie60", "rainbow swirl star" },
            { "86961", "rainbow swirl clover" },
            { "alcremie61", "rainbow swirl clover" },
            { "86962", "rainbow swirl flower" },
            { "alcremie62", "rainbow swirl flower" },
            { "86963", "rainbow swirl ribbon" },
            { "alcremie63", "rainbow swirl ribbon" }
        };
    }
}
