using System.Collections.Generic;

namespace TextStrings
{
    public static class Food
    {
        public static List<string> List = new List<string> {
      "asparagus",
      "apples",
      "avocado",
      "alfalfa",
      "acorn squash",
      "almond",
      "arugula",
      "artichoke",
      "applesauce",
      "Asian noodles",
      "antelope",
      "ahi tuna",
      "albacore tuna",
      "apple juice",
      "avocado roll",
      "bruschetta",
      "bacon",
      "black beans",
      "bagels",
      "baked beans",
      "BBQ",
      "bison",
      "barley",
      "beer",
      "bisque",
      "bluefish",
      "bread",
      "broccoli",
      "burrito",
      "baba ganoush",
      "cabbage",
      "cake",
      "carrots",
      "carne asada",
      "celery",
      "cheese",
      "chicken",
      "catfish",
      "chips",
      "chocolate",
      "chowder",
      "clams",
      "coffee",
      "cookies",
      "corn",
      "cupcakes",
      "crab",
      "curry",
      "cereal",
      "chimichanga",
      "dates",
      "dips",
      "duck",
      "dumplings",
      "donuts",
      "eggs",
      "enchilada",
      "egg rolls",
      "English muffins",
      "edamame",
      "eel sushi",
      "fajita",
      "falafel",
      "fish",
      "franks",
      "fondue",
      "French toast",
      "French dip",
      "garlic",
      "ginger",
      "gnocchi",
      "goose",
      "granola",
      "grapes",
      "green beans",
      "guacamole",
      "gumbo",
      "grits",
      "graham crackers",
      "ham",
      "halibut",
      "hamburger",
      "honey",
      "huevos rancheros",
      "hash browns",
      "hot dogs",
      "haiku roll",
      "hummus",
      "ice cream",
      "Irish stew",
      "Indian food",
      "Italian bread",
      "jambalaya",
      "jelly / jam",
      "jerky",
      "jalapeño",
      "kale",
      "kabobs",
      "ketchup",
      "kiwi",
      "kidney beans",
      "kingfish",
      "lobster",
      "lamb",
      "linguine",
      "lasagna",
      "meatballs",
      "moose",
      "milk",
      "milkshake",
      "noodles",
      "ostrich",
      "pizza",
      "pepperoni",
      "porter",
      "pancakes",
      "quesadilla",
      "quiche",
      "reuben",
      "spinach",
      "spaghetti",
      "tater tots",
      "toast",
      "waffles",
      "wine",
      "walnuts",
      "yogurt",
      "ziti",
      "zucchini",
      "marmalade",
      "soymilk",
      "sweet peppers",
      "pumpkins",
      "arugula",
      "chocolate",
      "hoisin sauce",
      "apple butter",
      "cauliflower",
      "chicory",
      "apricots",
      "breadcrumbs",
      "sushi",
      "parsnips",
      "honeydew melons",
      "hazelnuts",
      "eggs",
      "yogurt",
      "zest",
      "peanut butter",
      "passion fruit",
      "dill",
      "sea cucumbers",
      "turtle",
      "limes",
      "water",
      "tofu",
      "chard",
      "Tabasco sauce",
      "trout",
      "swiss cheese",
      "sausages",
      "bacon grease",
      "applesauce",
      "cayenne pepper",
      "curry powder",
      "amaretto",
      "cactus",
      "radishes",
      "chives",
      "almonds",
      "cucumbers",
      "haddock",
      "squid",
      "pears",
      "spearmint",
      "feta cheese",
      "chutney",
      "lettuce",
      "marshmallows",
      "acorn squash",
      "cookies",
      "pig's feet",
      "vinegar",
      "turkeys",
      "quail",
      "baguette",
      "mackerel",
      "thyme",
      "halibut",
      "corn flour",
      "habanero chilies",
      "English muffins",
      "colby cheese",
      "remoulade",
      "shallots",
      "rose water",
      "anchovy paste",
      "vanilla bean",
      "Havarti cheese",
      "rabbits",
      "powdered sugar",
      "chicken",
      "cider vinegar",
      "almond paste",
      "coriander",
      "okra",
      "split peas",
      "lemon juice",
      "cabbage",
      "vanilla",
      "caviar",
      "salmon",
      "cornstarch",
      "sauerkraut",
      "granola",
      "broccoli",
      "red chile powder",
      "raspberries",
      "tortillas",
      "corn syrup",
      "plantains",
      "blue cheese",
      "jicama",
      "rosemary",
      "mesclun greens",
      "adobo",
      "chai",
      "pheasants",
      "tonic water",
      "oregano",
      "prunes",
      "garlic",
      "beef",
      "pumpkin seeds",
      "venison",
      "oranges",
      "barley",
      "vegemite",
      "black olives",
      "cashew nut",
      "mozzarella",
      "tomatoes",
      "molasses",
      "watermelons",
      "pine nuts",
      "capers",
      "baking soda",
      "balsamic vinegar",
      "cornmeal",
      "Marsala",
      "steak",
      "poppy seeds",
      "bean threads",
      "blueberries",
      "crabs",
      "dates",
      "date sugar",
      "flour",
      "spinach",
      "oatmeal",
      "apples",
      "bouillon",
      "nectarines",
      "rum",
      "liver",
      "melons",
      "pasta",
      "kidney beans",
      "bass",
      "milk",
      "baking powder",
      "Kahlua",
      "figs",
      "tartar sauce",
      "octopus",
      "poultry seasoning",
      "Irish cream liqueur",
      "pecans",
      "tomato sauce",
      "swordfish",
      "sherry",
      "alligator",
      "scallops",
      "sage",
      "focaccia",
      "black-eyed peas",
      "corned beef",
      "jelly beans",
      "basil",
      "chaurice sausage",
      "bean sprouts",
      "mushrooms",
      "anchovies",
      "creme fraiche",
      "dumpling",
      "coconut oil",
      "peaches",
      "chipotle peppers",
      "prawns",
      "ginger ale",
      "soybeans",
      "blackberries",
      "andouille sausage",
      "cheddar cheese",
      "ketchup",
      "truffles",
      "five-spice powder",
      "olives",
      "tarragon",
      "huckleberries",
      "pink beans",
      "plum tomatoes",
      "wine",
      "unsweetened chocolate",
      "flax seed",
      "water chestnuts",
      "celery",
      "Cappuccino Latte",
      "maraschino cherries",
      "red beans",
      "onion powder",
      "zinfandel wine",
      "ham",
      "coconuts",
      "brown rice",
      "bard",
      "Parmesan cheese",
      "catfish",
      "spaghetti squash",
      "half-and-half",
      "cherries",
      "green onions",
      "coffee",
      "alfredo sauce",
      "brandy",
      "avocados",
      "mascarpone",
      "peas",
      "chambord",
      "beets",
      "chicken liver",
      "fennel",
      "clams",
      "portabella mushrooms",
      "eel",
      "chile peppers",
      "wasabi",
      "pickles",
      "bacon",
      "fish sauce",
      "gouda",
      "aquavit",
      "couscous",
      "chili powder",
      "rice vinegar",
      "snap peas",
      "bananas",
      "corn",
      "lima beans",
      "geese",
      "herring",
      "Mandarin oranges",
      "celery seeds",
      "chili sauce",
      "leeks",
      "mayonnaise",
      "ricotta cheese",
      "green beans",
      "kale",
      "almond extract",
      "pico de gallo",
      "cranberries",
      "heavy cream",
      "sweet potatoes",
      "mustard seeds",
      "rhubarb",
      "beans",
      "borscht",
      "honey",
      "red pepper flakes",
      "lemons",
      "shitakes",
      "rice paper",
      "cinnamon",
      "tuna",
      "kiwi",
      "asparagus",
      "sunflower seeds",
      "grits",
      "croutons",
      "potato chips",
      "rice",
      "pepper",
      "paprika",
      "succotash",
      "breadfruit",
      "salt",
      "won ton skins",
      "romaine lettuce",
      "horseradish",
      "monkfish",
      "Worcestershire sauce",
      "grapefruits",
      "dried leeks",
      "strawberries",
      "bean sauce",
      "brussels sprouts",
      "red cabbage",
      "walnuts",
      "hamburger",
      "navy beans",
      "snapper",
      "soy sauce",
      "pesto",
      "gelatin",
      "cider",
      "hot sauce",
      "brunoise",
      "cottage cheese",
      "panko bread crumbs",
      "bok choy",
      "maple syrup",
      "margarine",
      "black beans",
      "broth",
      "beer",
      "flounder",
      "orange peels",
      "apple pie spice",
      "barley sugar",
      "sazon",
      "fennel seeds",
      "moo shu wrappers",
      "grapes",
      "aioli",
      "tea",
      "cream cheese",
      "bagels",
      "condensed milk",
      "sugar",
      "chickpeas",
      "macaroni",
      "grouper",
      "salsa",
      "curry paste",
      "shrimp",
      "buttermilk",
      "sesame seeds",
      "pistachios",
      "graham crackers",
      "bay leaves",
      "cumin",
      "pineapples",
      "brown sugar",
      "onions",
      "parsley",
      "summer squash",
      "prosciutto",
      "curry leaves",
      "artificial sweetener",
      "pancetta",
      "plums",
      "broccoli raab",
      "garlic powder",
      "wine vinegar",
      "lobsters",
      "mustard",
      "cremini mushrooms",
      "eggplants",
      "hash browns",
      "custard",
      "lemon Peel",
      "sour cream",
      "duck",
      "asiago cheese",
      "tomato juice",
      "wild rice",
      "gorgonzola",
      "pomegranates",
      "lamb",
      "ginger",
      "angelica",
      "ancho chile peppers",
      "butter",
      "cream",
      "cocoa powder",
      "lemon grass",
      "cod",
      "lentils",
      "provolone",
      "pea beans",
      "pinto beans",
      "pork",
      "canola oil",
      "artichokes",
      "potatoes",
      "cantaloupes",
      "sweet chili sauce",
      "chestnuts",
      "tomato puree",
      "berries",
      "cream of tartar",
      "red snapper",
      "carrots",
      "coconut milk",
      "raisins",
      "papayas",
      "white beans",
      "olive oil",
      "cilantro",
      "sardines",
      "Romano cheese",
      "raw sugar",
      "allspice",
      "mint",
      "brazil nuts",
      "almond butter",
      "white chocolate",
      "jack cheese",
      "barbecue sauce",
      "guavas",
      "squash",
      "ice cream",
      "snow peas",
      "tomato paste",
      "cooking wine",
      "Canadian bacon",
      "kumquats",
      "ale",
      "bruschetta",
      "rice wine",
      "turnips",
      "bourbon",
      "crayfish",
      "veal",
      "cannellini beans",
      "vermouth",
      "mussels",
      "peanuts",
      "buckwheat",
      "cloves",
      "french fries",
      "Goji berry",
    };
    }
}