using System.Collections.Generic;

namespace TextStrings
{
    public static class Food
    {
        public static List<string> List = new List<string>
        {
            "abalone",
            "acorn squash",
            "ahi tuna",
            "aioli",
            "albacore tuna",
            "ale",
            "alfalfa",
            "alligator",
            "almonds",
            "anchovies",
            "andouille sausage",
            "anpan",
            "antelope",
            "apple juice",
            "apple pie",
            "apples",
            "applesauce",
            "apricots",
            "arepas",
            "artichoke",
            "arugula",
            "asiago cheese",
            "asparagus",
            "avocado",
            "baba ganoush",
            "bacon",
            "baked beans",
            "baklava",
            "balsamic vinegar",
            "banana",
            "banh mi",
            "baozi",
            "barbecue sauce",
            "basmati rice",
            "bass",
            "bean sprouts",
            "beans",
            "beef brisket",
            "beef jerky",
            "beef noodle soup",
            "beer",
            "beets",
            "bibimbap",
            "biryani",
            "bison",
            "bisque",
            "black beans",
            "black forest cake",
            "black olives",
            "blackberries",
            "blue cheese",
            "blueberries",
            "bluefish",
            "bocconcini",
            "bok choy",
            "bonbons",
            "bonito",
            "borscht",
            "bouillon",
            "bourbon",
            "brandy",
            "brazil nuts",
            "bread",
            "brie",
            "broccoli",
            "brown rice",
            "brownies",
            "brunoise",
            "bruschetta",
            "brussels sprouts",
            "bubble tea",
            "buckwheat noodles",
            "buffalo wings",
            "bulgogi",
            "burritos",
            "butter",
            "butter chicken",
            "butter tarts",
            "butterscotch",
            "cabbage",
            "cactus",
            "cake",
            "camembert cheese",
            "canadian bacon",
            "candy",
            "cannellini beans",
            "cantaloupe",
            "capers",
            "cappuccino latte",
            "caprese",
            "caramel",
            "carne asada",
            "carpaccio",
            "carrot cake",
            "carrots",
            "cashew nuts",
            "castellas",
            "catfish",
            "cauliflower",
            "caviar",
            "celery",
            "cereal",
            "cevapi",
            "ceviche",
            "chambord",
            "char siu pork",
            "chard",
            "chaurice sausage",
            "cheddar cheese",
            "cheesecake",
            "cheese",
            "cheeseburgers",
            "cherries",
            "chestnuts",
            "chicken",
            "chicken noodle soup",
            "chickpea curry",
            "chickpeas",
            "chicory",
            "chili peppers",
            "chili sauce",
            "chimichangas",
            "chipotle peppers",
            "chips",
            "chives",
            "chocolate",
            "chocolate cake",
            "chocolate chip cookies",
            "chocolate mousse",
            "chow mein",
            "chowder",
            "churros",
            "chutney",
            "ciabatta",
            "cider",
            "cinnamon rolls",
            "clam chowder",
            "clams",
            "cobb salad",
            "coconut milk",
            "coconuts",
            "cod",
            "coffee",
            "colby cheese",
            "coleslaw",
            "congee",
            "cookies",
            "corn",
            "cornbread",
            "corned beef",
            "cornmeal",
            "cottage cheese",
            "couscous",
            "crab",
            "crab cakes",
            "cranberries",
            "crayfish",
            "cream cheese",
            "creme fraiche",
            "cremini mushrooms",
            "crepes",
            "croissants",
            "croutons",
            "cucumbers",
            "cupcakes",
            "curry",
            "currywurst",
            "custard",
            "dal bhat",
            "dango",
            "dates",
            "dim sum",
            "dolma",
            "donuts",
            "dorayaki",
            "duck",
            "dumplings",
            "edamame",
            "eel",
            "egg rolls",
            "egg tarts",
            "eggplant",
            "eggs",
            "empanadas",
            "enchiladas",
            "english muffins",
            "fajitas",
            "falafel",
            "feta cheese",
            "figs",
            "fish",
            "fish and chips",
            "flax seeds",
            "flounder",
            "focaccia",
            "fondue",
            "french fries",
            "french toast",
            "fruitcake",
            "fudge",
            "funnel cake",
            "garlic",
            "gelato",
            "gimbap",
            "ginger ale",
            "gingerbread cookies",
            "gnocchi",
            "goji berries",
            "goose",
            "gorgonzola cheese",
            "gouda cheese",
            "goulash",
            "graham crackers",
            "granola",
            "grapefruit",
            "grapes",
            "gravy",
            "green beans",
            "green onions",
            "green peppers",
            "green tea",
            "grits",
            "grouper",
            "gruyere cheese",
            "guacamole",
            "guavas",
            "guinness",
            "gumbo",
            "gyoza",
            "gyro",
            "habanero chilies",
            "haddock",
            "haggis",
            "halibut",
            "ham",
            "hamburgers",
            "hash browns",
            "havarti cheese",
            "hazelnuts",
            "herring",
            "hoisin sauce",
            "hollandaise sauce",
            "honey",
            "honeydew",
            "horseradish",
            "hot and sour soup",
            "hot chocolate",
            "hot dogs",
            "hot sauce",
            "huckleberries",
            "huevos rancheros",
            "hummus",
            "ice cream",
            "irish cream liqueur",
            "irish stew",
            "jack cheese",
            "jalapenos",
            "jambalaya",
            "japchae",
            "jelly beans",
            "jerk chicken",
            "jicama",
            "kabobs",
            "kahlua",
            "kale",
            "karaage",
            "ketchup",
            "ketchup chips",
            "key lime pie",
            "kidney beans",
            "kimchi",
            "kingfish",
            "kiwis",
            "kofta",
            "kompot",
            "kumquats",
            "kung pao chicken",
            "kvass",
            "lamb",
            "lamb vindaloo",
            "lasagna",
            "lassi",
            "leeks",
            "lemon juice",
            "lemon meringue pie",
            "lemons",
            "lentils",
            "lettuce",
            "lima beans",
            "limes",
            "linguine",
            "liquorice",
            "lobster",
            "lobster rolls",
            "macadamia nuts",
            "macaroni",
            "macarons",
            "macaroons",
            "mackerel",
            "mandarin oranges",
            "mandu",
            "maple syrup",
            "mapo tofu",
            "marmalade",
            "marsala",
            "marshmallows",
            "marzipan",
            "masala chai",
            "mascarpone",
            "mashed potatoes",
            "mayonnaise",
            "meat pie",
            "meatballs",
            "meatloaf",
            "melonpan",
            "milk",
            "milk tea",
            "milkshake",
            "miso soup",
            "mochi",
            "molasses",
            "monkfish",
            "monterey jack cheese",
            "mooncake",
            "moose",
            "mozzarella cheese",
            "mushrooms",
            "mussels",
            "mustard",
            "naan",
            "nachos",
            "nanaimo bars",
            "natto",
            "nectarines",
            "nihari",
            "noodles",
            "nougat",
            "oatmeal",
            "octopus",
            "okonomiyaki",
            "okra",
            "olives",
            "omurice",
            "onigiri",
            "onions",
            "oranges",
            "ostrich",
            "pad thai",
            "paella",
            "pancakes",
            "pancetta",
            "papayas",
            "parmesan cheese",
            "parsnips",
            "passion fruit",
            "pasta",
            "pavlova",
            "peaches",
            "peanut butter",
            "peanuts",
            "pears",
            "peas",
            "pecans",
            "peking duck",
            "pepperoni",
            "pesto",
            "pheasant",
            "pho",
            "pickles",
            "pico de gallo",
            "pierogi",
            "pine nuts",
            "pineapples",
            "pistachios",
            "pizza",
            "plantains",
            "plums",
            "polenta",
            "pomegranates",
            "poppy seeds",
            "pork",
            "portabella mushrooms",
            "potato chips",
            "potatoes",
            "potstickers",
            "poutine",
            "prawns",
            "pretzels",
            "prosciutto",
            "provolone",
            "prunes",
            "pumpkin",
            "pumpkin seeds",
            "quail",
            "quesadilla",
            "quiche",
            "rabbit",
            "rabbit stew",
            "radishes",
            "raisins",
            "ramen",
            "raspberries",
            "ravioli",
            "red beans",
            "red cabbage",
            "red snapper",
            "red wine",
            "relish",
            "remoulade",
            "reuben",
            "rhubarb",
            "ribs",
            "rice",
            "ricotta cheese",
            "risotto",
            "roast beef",
            "roast lamb",
            "romaine lettuce",
            "roquefort cheese",
            "rum",
            "sake",
            "salmon",
            "salsa",
            "saltfish",
            "samosas",
            "sardines",
            "sashimi",
            "satay",
            "sauerkraut",
            "sausages",
            "scallops",
            "schnitzel",
            "sea cucumber",
            "sesame seeds",
            "shallots",
            "shepherd's pie",
            "sherry",
            "shiitake mushrooms",
            "shrimp",
            "smoked salmon",
            "s'mores",
            "snap peas",
            "snapper",
            "snow peas",
            "soba",
            "soda",
            "sorbet",
            "sour cream",
            "souvlaki",
            "soy sauce",
            "soybeans",
            "soy milk",
            "spaghetti",
            "spinach",
            "spring rolls",
            "squash",
            "squid",
            "sriracha sauce",
            "stamppot",
            "steak",
            "steak frites",
            "strawberries",
            "stroopwafel",
            "strudel",
            "succotash",
            "summer squash",
            "sunflower seeds",
            "sushi",
            "sweet and sour pork",
            "sweet chili sauce",
            "sweet potatoes",
            "swiss cheese",
            "swordfish",
            "tabasco sauce",
            "tacos",
            "tagine",
            "tahini",
            "taiyaki",
            "takoyaki",
            "tamagoyaki",
            "tandoori chicken",
            "tartar sauce",
            "tater tots",
            "tea",
            "tempura",
            "tequila",
            "tikka masala",
            "tiramisu",
            "toast",
            "tofu",
            "tom yum",
            "tomato juice",
            "tomatoes",
            "tonkatsu",
            "tortellini",
            "tortillas",
            "trout",
            "truffle oil",
            "truffles",
            "tuna",
            "turkeys",
            "turkish delight",
            "turnips",
            "turtle",
            "udon",
            "vanilla ice cream",
            "veal",
            "vegemite",
            "venison",
            "vermouth",
            "waffles",
            "walnuts",
            "wasabi",
            "water",
            "water chestnuts",
            "watermelons",
            "white chocolate",
            "white wine",
            "wings",
            "wontons",
            "worcestershire sauce",
            "yams",
            "yogurt",
            "ziti",
            "zucchini",
        };
    }
}
