using System.Collections.Generic;

namespace TextStrings
{
    public static class Food
    {
        public static List<string> List = new List<string>
        {
            "asparagus",
            "apples",
            "avocado",
            "alfalfa",
            "acorn squash",
            "almond",
            "arugula",
            "artichoke",
            "applesauce",
            "Asian noodles",
            "antelope",
            "ahi tuna",
            "albacore tuna",
            "apple juice",
            "avocado roll",
            "bruschetta",
            "bacon",
            "black beans",
            "bagels",
            "baked beans",
            "BBQ",
            "bison",
            "barley",
            "beer",
            "bisque",
            "bluefish",
            "bread",
            "broccoli",
            "burrito",
            "baba ganoush",
            "cabbage",
            "cake",
            "carrots",
            "carne asada",
            "celery",
            "cheese",
            "chicken",
            "catfish",
            "chips",
            "chocolate",
            "chowder",
            "clams",
            "coffee",
            "cookies",
            "corn",
            "cupcakes",
            "crab",
            "curry",
            "cereal",
            "chimichanga",
            "dates",
            "dips",
            "duck",
            "dumplings",
            "donuts",
            "eggs",
            "enchilada",
            "egg rolls",
            "English muffins",
            "edamame",
            "eel sushi",
            "fajita",
            "falafel",
            "fish",
            "franks",
            "fondue",
            "French toast",
            "French dip",
            "garlic",
            "ginger",
            "gnocchi",
            "goose",
            "granola",
            "grapes",
            "green beans",
            "guacamole",
            "gumbo",
            "grits",
            "graham crackers",
            "ham",
            "halibut",
            "hamburger",
            "honey",
            "huevos rancheros",
            "hash browns",
            "hot dogs",
            "haiku roll",
            "hummus",
            "ice cream",
            "Irish stew",
            "Indian food",
            "Italian bread",
            "jambalaya",
            "jelly / jam",
            "jerky",
            "jalapeño",
            "kale",
            "kabobs",
            "ketchup",
            "kiwi",
            "kidney beans",
            "kingfish",
            "lobster",
            "lamb",
            "linguine",
            "lasagna",
            "meatballs",
            "moose",
            "milk",
            "milkshake",
            "noodles",
            "ostrich",
            "pizza",
            "pepperoni",
            "porter",
            "pancakes",
            "quesadilla",
            "quiche",
            "reuben",
            "spinach",
            "spaghetti",
            "tater tots",
            "toast",
            "waffles",
            "wine",
            "walnuts",
            "yogurt",
            "ziti",
            "zucchini"
        };
    }
}
